# -*- coding: utf-8 -*-
"""Moduł V, rozdziały 15-16: teoria kinetyczna i termodynamika. CC BY-SA 4.0."""

P = [
 dict(id="M5t-01", modul="M5", rozdzial="15.1",
  pytanie="Z punktu widzenia teorii kinetycznej ciśnienie gazu jest skutkiem:",
  odp=["Zderzeń cząsteczek ze ściankami naczynia",
       "Ciężaru gazu", "Odpychania się cząsteczek", "Ruchu naczynia"],
  ok=0,
  wyj="Każde zderzenie to przekazanie pędu ściance. Im więcej i im silniejszych zderzeń, tym większe ciśnienie."),

 dict(id="M5t-02", modul="M5", rozdzial="15.2.2",
  pytanie="Temperatura bezwzględna gazu doskonałego jest miarą:",
  odp=["Średniej energii kinetycznej ruchu postępowego cząsteczek",
       "Całkowitej energii gazu",
       "Ilości ciepła zawartego w gazie",
       "Prędkości najszybszej cząsteczki"],
  ok=0,
  wyj="Ciepło to nie to samo co temperatura — jest formą przekazywania energii, a nie jej zasobem. Dwa ciała o tej samej temperaturze mogą mieć różną energię wewnętrzną."),

 dict(id="M5t-03", modul="M5", rozdzial="15.2.3",
  pytanie="Gaz w zamkniętym sztywnym zbiorniku ogrzano z 300 K do 600 K. Jak zmieniło się ciśnienie?",
  odp=["Wzrosło dwukrotnie", "Wzrosło czterokrotnie",
       "Nie zmieniło się", "Wzrosło o 300 jednostek"],
  ok=0,
  wyj="Przy stałej objętości ciśnienie jest proporcjonalne do temperatury bezwzględnej. Uwaga: gdyby dane były w stopniach Celsjusza, trzeba je najpierw zamienić na kelwiny."),

 dict(id="M5t-04", modul="M5", rozdzial="15.2.3",
  pytanie="Które przybliżenie NIE jest częścią modelu gazu doskonałego?",
  odp=["Cząsteczki przyciągają się na odległość",
       "Objętość własna cząsteczek jest pomijalna",
       "Zderzenia są doskonale sprężyste",
       "Ruch cząsteczek jest chaotyczny"],
  ok=0,
  wyj="Model zakłada BRAK oddziaływań na odległość. Uwzględnia je dopiero równanie Van der Waalsa, dzięki czemu opisuje skraplanie."),

 dict(id="M5t-05", modul="M5", rozdzial="15.3",
  pytanie="Ile stopni swobody ma cząsteczka gazu dwuatomowego w temperaturze pokojowej?",
  odp=["Pięć: trzy postępowe i dwa obrotowe",
       "Trzy postępowe", "Sześć", "Siedem, łącznie z drganiami"],
  ok=0,
  wyj="Drgania wzdłuż wiązania wymagają wyższych temperatur, żeby się wzbudzić. Stąd ciepło molowe azotu to 5/2 R, a nie 7/2 R."),

 dict(id="M5t-06", modul="M5", rozdzial="15.4",
  pytanie="Gaz otrzymał 800 J ciepła i wykonał 300 J pracy. Jak zmieniła się jego energia wewnętrzna?",
  odp=["Wzrosła o 500 J", "Wzrosła o 1100 J", "Zmalała o 500 J", "Nie zmieniła się"],
  ok=0,
  wyj=r"$\Delta U = Q - W = 800 - 300 = 500$ J. Pilnowanie znaków to najczęstsza pułapka w tym dziale."),

 dict(id="M5t-07", modul="M5", rozdzial="15.6.1",
  pytanie="Które stwierdzenie o przemianie izotermicznej gazu doskonałego jest prawdziwe?",
  odp=["Całe pobrane ciepło zamienia się w pracę",
       "Całe ciepło idzie na wzrost energii wewnętrznej",
       "Nie ma wymiany ciepła",
       "Praca jest zerowa"],
  ok=0,
  wyj=r"Energia wewnętrzna gazu doskonałego zależy tylko od temperatury, więc przy $T$ = const mamy $\Delta U = 0$, czyli $Q = W$."),

 dict(id="M5t-08", modul="M5", rozdzial="15.6.2",
  pytanie="Dlaczego gaz rozprężany adiabatycznie stygnie?",
  odp=["Bo pracę wykonuje kosztem własnej energii wewnętrznej",
       "Bo oddaje ciepło otoczeniu",
       "Bo maleje jego masa",
       "Bo rośnie liczba cząsteczek"],
  ok=0,
  wyj="Adiabata oznacza brak wymiany ciepła, więc praca może pochodzić wyłącznie z energii wewnętrznej, a jej spadek to spadek temperatury."),

 dict(id="M5t-09", modul="M5", rozdzial="16.2",
  pytanie="W rozkładzie Maxwella wraz ze wzrostem temperatury krzywa:",
  odp=["Spłaszcza się i przesuwa w stronę wyższych prędkości",
       "Zwęża się i przesuwa w lewo",
       "Nie zmienia kształtu",
       "Staje się symetryczna"],
  ok=0,
  wyj="Pole pod krzywą pozostaje stałe, bo liczba cząsteczek się nie zmienia. Wzrost temperatury poszerza rozkład."),

 dict(id="M5t-10", modul="M5", rozdzial="16.2",
  pytanie="Które cząsteczki poruszają się szybciej w tej samej temperaturze?",
  odp=["Lżejsze", "Cięższe", "Obie tak samo", "Zależy to od ciśnienia"],
  ok=0,
  wyj=r"$v_{\mathrm{rms}}=\sqrt{3RT/M}$ — przy równej energii kinetycznej mniejsza masa oznacza większą prędkość. Dlatego wodór ucieka z atmosfery, a azot nie."),

 dict(id="M5t-11", modul="M5", rozdzial="16.4",
  pytanie="Silnik cieplny pobiera 1000 J z grzejnicy i oddaje 700 J do chłodnicy. Jaka jest jego sprawność?",
  odp=["30%", "70%", "100%", "43%"],
  ok=0,
  wyj=r"$\eta = W/Q_1 = 300/1000 = 30\%$. Silnik musi oddać część ciepła chłodnicy — bez tego łamałby drugą zasadę termodynamiki."),

 dict(id="M5t-12", modul="M5", rozdzial="16.4.2",
  pytanie="Silnik Carnota pracuje między 500 K a 300 K. Jaka jest jego maksymalna sprawność?",
  odp=["40%", "60%", "167%", "20%"],
  ok=0,
  wyj=r"$\eta = 1 - 300/500 = 0{,}4$. Żaden rzeczywisty silnik między tymi temperaturami nie przekroczy tej wartości."),

 dict(id="M5t-13", modul="M5", rozdzial="16.5",
  pytanie="Które sformułowanie drugiej zasady termodynamiki jest poprawne?",
  odp=["Niemożliwy jest proces, którego jedynym skutkiem jest przekazanie ciepła od ciała chłodniejszego do cieplejszego",
       "Energia nie może być ani stworzona, ani zniszczona",
       "Każdy silnik może mieć sprawność 100%",
       "Entropia układu izolowanego zawsze maleje"],
  ok=0,
  wyj="To sformułowanie Clausiusa. Lodówka przenosi ciepło w tę stronę, ale kosztem pracy, więc nie jest to JEDYNY skutek."),

 dict(id="M5t-14", modul="M5", rozdzial="16.5.2",
  pytanie="W procesie odwracalnym w układzie izolowanym entropia:",
  odp=["Nie zmienia się", "Zawsze rośnie", "Zawsze maleje", "Zmienia się losowo"],
  ok=0,
  wyj="Równość dotyczy procesów odwracalnych, czyli idealizacji. Wszystkie procesy rzeczywiste zwiększają entropię."),

 dict(id="M5t-15", modul="M5", rozdzial="16.5.3",
  pytanie="Entropia jest miarą:",
  odp=["Liczby mikrostanów odpowiadających danemu stanowi makroskopowemu",
       "Ilości ciepła w ciele",
       "Temperatury ciała",
       "Energii wewnętrznej"],
  ok=0,
  wyj="To interpretacja Boltzmanna. Stan nieuporządkowany ma nieporównanie więcej realizacji, dlatego układ dąży właśnie do niego."),

 dict(id="M5t-16", modul="M5", rozdzial="16.6",
  pytanie="Trzecia zasada termodynamiki mówi, że:",
  odp=["Nie da się osiągnąć temperatury zera bezwzględnego w skończonej liczbie kroków",
       "Energia jest zachowana",
       "Entropia zawsze rośnie",
       "Ciepło przechodzi od ciała cieplejszego do chłodniejszego"],
  ok=0,
  wyj="W miarę zbliżania się do zera bezwzględnego każdy kolejny stopień chłodzenia wymaga coraz więcej pracy. Osiągnięto już temperatury rzędu miliardowych części kelwina, ale nie zero."),
]
