# -*- coding: utf-8 -*-
"""Moduł VIII, rozdziały 24-27: indukcja, drgania i fale elektromagnetyczne. CC BY-SA 4.0."""

P = [
 dict(id="M8i-01", modul="M8", rozdzial="24.1",
  pytanie="Od czego zależy siła elektromotoryczna indukcji?",
  odp=["Od szybkości zmiany strumienia magnetycznego",
       "Od wartości strumienia",
       "Od indukcji pola magnetycznego",
       "Od oporu obwodu"],
  ok=0,
  wyj="Nieruchoma ramka w stałym polu nie generuje SEM, choćby pole było bardzo silne. Liczy się wyłącznie tempo zmian."),

 dict(id="M8i-02", modul="M8", rozdzial="24.2",
  pytanie="Magnes zbliża się biegunem północnym do pętli. Jak skierowany jest prąd indukcyjny?",
  odp=["Tak, by wytworzyć biegun północny zwrócony do magnesu i go odpychać",
       "Tak, by przyciągnąć magnes",
       "Prąd nie popłynie",
       "Kierunek jest przypadkowy"],
  ok=0,
  wyj="To reguła Lenza. Gdyby prąd przyciągał magnes, dostalibyśmy przyspieszenie za darmo, czyli perpetuum mobile."),

 dict(id="M8i-03", modul="M8", rozdzial="24.2",
  pytanie="Magnes spadający przez miedzianą rurę porusza się wolniej niż w powietrzu, ponieważ:",
  odp=["Prądy wirowe wytwarzają pole przeciwdziałające ruchowi",
       "Miedź jest ferromagnetykiem",
       "Rura zwiększa opór powietrza",
       "Magnes przykleja się do ścianek"],
  ok=0,
  wyj="Miedź nie jest magnetyczna, ale dobrze przewodzi. Na tym opiera się hamowanie indukcyjne w pociągach i na kolejkach górskich."),

 dict(id="M8i-04", modul="M8", rozdzial="24.3.1",
  pytanie="Dlaczego transformator nie działa na prąd stały?",
  odp=["Bo strumień magnetyczny jest wtedy stały i nie indukuje SEM",
       "Bo prąd stały nie wytwarza pola magnetycznego",
       "Bo uzwojenie by się przepaliło",
       "Bo rdzeń nie przewodzi prądu stałego"],
  ok=0,
  wyj="Prąd stały wytwarza pole, ale niezmienne w czasie. Bez zmian strumienia nie ma indukcji."),

 dict(id="M8i-05", modul="M8", rozdzial="24.3.1",
  pytanie="Transformator ma 500 zwojów pierwotnych i 100 wtórnych. Napięcie wejściowe to 230 V. Ile wynosi wyjściowe?",
  odp=["46 V", "1150 V", "230 V", "23 V"],
  ok=0,
  wyj=r"$U_2 = U_1 n_2/n_1 = 230/5 = 46$ V. Prąd rośnie w tym samym stosunku, bo moc jest w przybliżeniu zachowana."),

 dict(id="M8i-06", modul="M8", rozdzial="24.3.2",
  pytanie="Dlaczego przy rozłączaniu obwodu z cewką powstaje iskra?",
  odp=["Bo gwałtowna zmiana prądu indukuje wysokie napięcie samoindukcji",
       "Bo cewka gromadzi ładunek elektryczny",
       "Bo rośnie opór styków",
       "Bo cewka się przegrzewa"],
  ok=0,
  wyj=r"$\varepsilon = -L\,dI/dt$. Przy bardzo szybkiej zmianie prądu napięcie może wielokrotnie przekroczyć napięcie zasilania. Z tego korzysta cewka zapłonowa."),

 dict(id="M8i-07", modul="M8", rozdzial="25.1",
  pytanie="W obwodzie LC energia przechodzi cyklicznie:",
  odp=["Z pola elektrycznego kondensatora do pola magnetycznego cewki",
       "Z cewki do opornika",
       "Z kondensatora do źródła",
       "Zamienia się w ciepło"],
  ok=0,
  wyj="To elektryczny odpowiednik wahadła. Bez oporu drgania trwałyby bez końca; opór odpowiada tarciu."),

 dict(id="M8i-08", modul="M8", rozdzial="25.2",
  pytanie="Reaktancja cewki wraz ze wzrostem częstotliwości:",
  odp=["Rośnie", "Maleje", "Nie zmienia się", "Zmienia się losowo"],
  ok=0,
  wyj=r"$X_L = \omega L$ rośnie, a $X_C = 1/(\omega C)$ maleje. Dlatego cewka przepuszcza prąd stały, a kondensator go blokuje."),

 dict(id="M8i-09", modul="M8", rozdzial="25.3",
  pytanie="W szeregowym obwodzie RLC przy rezonansie:",
  odp=["Impedancja jest najmniejsza i równa R, a prąd największy",
       "Impedancja jest największa",
       "Prąd wynosi zero",
       "Napięcie na cewce wynosi zero"],
  ok=0,
  wyj="Reaktancje się znoszą, bo działają przeciwnie. Napięcia na cewce i kondensatorze mogą być wtedy wielokrotnie większe od zasilającego."),

 dict(id="M8i-10", modul="M8", rozdzial="25.4",
  pytanie="Idealna cewka w obwodzie prądu zmiennego:",
  odp=["Nie zużywa mocy czynnej, tylko wymienia energię ze źródłem",
       "Zamienia całą energię w ciepło",
       "Zwiększa moc czynną",
       "Nie przewodzi prądu zmiennego"],
  ok=0,
  wyj=r"Prąd i napięcie są przesunięte o $90^\circ$, więc średnia moc wynosi zero. Energia wraca do źródła w drugiej połowie okresu."),

 dict(id="M8i-11", modul="M8", rozdzial="26.1",
  pytanie="Które równanie Maxwella wyraża brak monopoli magnetycznych?",
  odp=[r"$\nabla\cdot\vec{B} = 0$", r"$\nabla\cdot\vec{E} = \rho/\varepsilon_0$",
       r"$\nabla\times\vec{E} = -\partial\vec{B}/\partial t$",
       r"$\nabla\times\vec{B} = \mu_0\vec{J}$"],
  ok=0,
  wyj="Strumień pola magnetycznego przez powierzchnię zamkniętą zawsze wynosi zero. Linie pola magnetycznego nie mają początku ani końca."),

 dict(id="M8i-12", modul="M8", rozdzial="26.3",
  pytanie="Czym jest prąd przesunięcia wprowadzony przez Maxwella?",
  odp=["Wkładem zmiennego pola elektrycznego, działającym jak prąd wytwarzający pole magnetyczne",
       "Prądem elektronów w dielektryku",
       "Prądem wirowym w rdzeniu",
       "Prądem upływu przez izolację"],
  ok=0,
  wyj="Bez tego członu równania byłyby sprzeczne przy ładowaniu kondensatora, a fale elektromagnetyczne nie mogłyby istnieć."),

 dict(id="M8i-13", modul="M8", rozdzial="27.1",
  pytanie="Które promieniowanie ma najkrótszą długość fali?",
  odp=["Gamma", "Rentgenowskie", "Nadfioletowe", "Mikrofale"],
  ok=0,
  wyj="Kolejność od najdłuższych: radiowe, mikrofale, podczerwień, widzialne, nadfiolet, rentgenowskie, gamma. Krótsza fala to wyższa energia fotonu."),

 dict(id="M8i-14", modul="M8", rozdzial="27.2",
  pytanie="Fala elektromagnetyczna do rozchodzenia się potrzebuje:",
  odp=["Nie potrzebuje żadnego ośrodka, biegnie także w próżni",
       "Ośrodka sprężystego",
       "Przewodnika",
       "Pola grawitacyjnego"],
  ok=0,
  wyj="To odróżnia ją od fal mechanicznych. Pole elektryczne i magnetyczne wzajemnie się podtrzymują, więc eter nie jest potrzebny."),

 dict(id="M8i-15", modul="M8", rozdzial="27.3",
  pytanie="Jak zmienia się natężenie fali elektromagnetycznej od źródła punktowego z odległością?",
  odp=["Maleje jak 1/r²", "Maleje jak 1/r", "Nie zmienia się", "Maleje wykładniczo"],
  ok=0,
  wyj="Ta sama moc rozkłada się na powierzchnię sfery rosnącą jak r². Amplituda pola maleje przy tym jak 1/r."),

 dict(id="M8i-16", modul="M8", rozdzial="27.4",
  pytanie="Co opisuje wektor Poyntinga?",
  odp=["Gęstość strumienia energii przenoszonej przez falę",
       "Kierunek pola elektrycznego",
       "Natężenie pola magnetycznego",
       "Polaryzację fali"],
  ok=0,
  wyj=r"$\vec{S} = \vec{E}\times\vec{H}$, w watach na metr kwadratowy. Jego kierunek pokrywa się z kierunkiem rozchodzenia się fali."),
]
