# -*- coding: utf-8 -*-
"""Moduly M9-M11: optyka, fizyka kwantowa, atomy i jadro. CC BY-SA 4.0."""

P = [
 # ---------------- M9: OPTYKA ----------------
 dict(id="M9-01", modul="M9", rozdzial="28",
  pytanie="Prawo załamania (prawo Snella) ma postać:",
  odp=[r"$n_1\sin\theta_1 = n_2\sin\theta_2$", r"$n_1\cos\theta_1 = n_2\cos\theta_2$",
       r"$\frac{\sin\theta_1}{n_1} = \frac{\sin\theta_2}{n_2}$", r"$n_1\theta_1 = n_2\theta_2$"],
  ok=0,
  wyj=r"Współczynnik załamania $n = \frac{c}{v}$. Przy przejściu do ośrodka gęstszego optycznie promień załamuje się ku normalnej."),

 dict(id="M9-02", modul="M9", rozdzial="28",
  pytanie="Całkowite wewnętrzne odbicie zachodzi, gdy:",
  odp=["Światło biegnie z ośrodka gęstszego do rzadszego pod kątem większym od granicznego",
       "Światło biegnie z ośrodka rzadszego do gęstszego",
       "Kąt padania wynosi zero",
       "Oba ośrodki mają ten sam współczynnik załamania"],
  ok=0,
  wyj=r"Kąt graniczny spełnia $\sin\theta_{gr} = \frac{n_2}{n_1}$. Na tym opiera się działanie światłowodu."),

 dict(id="M9-03", modul="M9", rozdzial="28",
  pytanie="Równanie soczewki cienkiej to:",
  odp=[r"$\frac{1}{f} = \frac{1}{x} + \frac{1}{y}$", r"$f = x + y$",
       r"$\frac{1}{f} = \frac{1}{x} - \frac{1}{y}$", r"$f = \frac{x y}{x + y}$"],
  ok=0,
  wyj=r"Zdolność skupiająca $Z = \frac{1}{f}$ wyrażona jest w dioptriach. Dla soczewki rozpraszającej $f < 0$."),

 dict(id="M9-04", modul="M9", rozdzial="29",
  pytanie="Warunek na jasne prążki w doświadczeniu Younga to:",
  odp=[r"$d\sin\theta = m\lambda$", r"$d\sin\theta = (m+\tfrac{1}{2})\lambda$",
       r"$d\cos\theta = m\lambda$", r"$\frac{d}{\sin\theta} = m\lambda$"],
  ok=0,
  wyj=r"Różnica dróg musi być całkowitą wielokrotnością długości fali. Warunek $(m+\tfrac{1}{2})\lambda$ daje prążki ciemne."),

 dict(id="M9-05", modul="M9", rozdzial="30",
  pytanie="Pierwsze minimum dyfrakcyjne na pojedynczej szczelinie o szerokości a występuje przy:",
  odp=[r"$a\sin\theta = \lambda$", r"$a\sin\theta = \tfrac{\lambda}{2}$",
       r"$a\sin\theta = 2\lambda$", r"$a\cos\theta = \lambda$"],
  ok=0,
  wyj="Im węższa szczelina, tym szersze maksimum centralne. Dyfrakcja ogranicza zdolność rozdzielczą przyrządów optycznych."),

 dict(id="M9-06", modul="M9", rozdzial="31",
  pytanie="Prawo Malusa opisujące natężenie światła za polaryzatorem to:",
  odp=[r"$I = I_0\cos^2\theta$", r"$I = I_0\cos\theta$", r"$I = I_0\sin^2\theta$", r"$I = \frac{I_0}{\cos^2\theta}$"],
  ok=0,
  wyj=r"Przy skrzyżowanych polaryzatorach ($\theta = 90^\circ$) światło nie przechodzi. Światło niespolaryzowane traci na pierwszym polaryzatorze połowę natężenia."),

 # ---------------- M10: FIZYKA KWANTOWA ----------------
 dict(id="M10-01", modul="M10", rozdzial="32",
  pytanie="Energia kwantu promieniowania (fotonu) wynosi:",
  odp=[r"$E = h\nu$", r"$E = \frac{h}{\nu}$", r"$E = h\nu^2$", r"$E = \frac{\nu}{h}$"],
  ok=0,
  wyj=r"$h \approx 6{,}63\cdot10^{-34}$ J·s. Równoważnie $E = \frac{hc}{\lambda}$. Hipoteza Plancka rozwiązała problem katastrofy w nadfiolecie."),

 dict(id="M10-02", modul="M10", rozdzial="32",
  pytanie="Równanie Einsteina dla zjawiska fotoelektrycznego ma postać:",
  odp=[r"$h\nu = W + E_{k,\max}$", r"$h\nu = W - E_{k,\max}$",
       r"$h\nu = \frac{W}{E_{k,\max}}$", r"$E_{k,\max} = h\nu \cdot W$"],
  ok=0,
  wyj=r"$W$ to praca wyjścia. Poniżej częstotliwości progowej zjawisko nie zachodzi niezależnie od natężenia światła — tego nie da się wyjaśnić falowo."),

 dict(id="M10-03", modul="M10", rozdzial="34",
  pytanie="Długość fali de Broglie'a cząstki o pędzie p wynosi:",
  odp=[r"$\lambda = \frac{h}{p}$", r"$\lambda = \frac{p}{h}$", r"$\lambda = hp$", r"$\lambda = \frac{h}{p^2}$"],
  ok=0,
  wyj="Każdej cząstce odpowiada fala. Dla obiektów makroskopowych długość fali jest tak mała, że efektów falowych nie obserwujemy."),

 dict(id="M10-04", modul="M10", rozdzial="35",
  pytanie="Zasada nieoznaczoności Heisenberga dla położenia i pędu brzmi:",
  odp=[r"$\Delta x\,\Delta p \geq \frac{\hbar}{2}$", r"$\Delta x\,\Delta p \leq \frac{\hbar}{2}$",
       r"$\Delta x + \Delta p \geq \hbar$", r"$\frac{\Delta x}{\Delta p} \geq \hbar$"],
  ok=0,
  wyj=r"To ograniczenie samej natury, nie niedoskonałość przyrządów. Analogiczna relacja wiąże energię i czas: $\Delta E\,\Delta t \geq \frac{\hbar}{2}$."),

 dict(id="M10-05", modul="M10", rozdzial="35",
  pytanie="Kwadrat modułu funkcji falowej określa:",
  odp=["Gęstość prawdopodobieństwa znalezienia cząstki",
       "Energię cząstki w danym punkcie",
       "Pęd cząstki",
       "Tor ruchu cząstki"],
  ok=0,
  wyj=r"To interpretacja Borna. Warunek normalizacji wymaga, żeby $\int|\psi|^2 dV = 1$ — cząstka gdzieś na pewno jest."),

 dict(id="M10-06", modul="M10", rozdzial="32",
  pytanie="Prawo przesunięć Wiena wiąże temperaturę ciała doskonale czarnego z:",
  odp=[r"Długością fali maksimum emisji: $\lambda_{\max} T = \mathrm{const}$",
       r"Całkowitą mocą wypromieniowaną: $P \sim T^4$",
       "Częstotliwością progową fotoefektu",
       "Energią jonizacji atomu"],
  ok=0,
  wyj=r"Im wyższa temperatura, tym krótsza fala maksimum — dlatego gorętsze gwiazdy świecą na niebiesko. Zależność $P \sim T^4$ to prawo Stefana-Boltzmanna."),

 # ---------------- M11: ATOMY, CIALO STALE, JADRO ----------------
 dict(id="M11-01", modul="M11", rozdzial="36",
  pytanie="Zakaz Pauliego mówi, że w atomie:",
  odp=["Dwa elektrony nie mogą mieć identycznego zestawu czterech liczb kwantowych",
       "Elektrony nie mogą zmieniać orbity",
       "Liczba elektronów nie może przekroczyć liczby protonów",
       "Elektron nie może znaleźć się w jądrze"],
  ok=0,
  wyj="To on wymusza budowę powłok elektronowych i tłumaczy układ okresowy. Bez niego wszystkie elektrony zajęłyby stan podstawowy."),

 dict(id="M11-02", modul="M11", rozdzial="36",
  pytanie="Energia poziomów w atomie wodoru dana jest wzorem:",
  odp=[r"$E_n = -\frac{13{,}6\ \mathrm{eV}}{n^2}$", r"$E_n = -\frac{13{,}6\ \mathrm{eV}}{n}$",
       r"$E_n = 13{,}6\,n^2\ \mathrm{eV}$", r"$E_n = -13{,}6\,n\ \mathrm{eV}$"],
  ok=0,
  wyj=r"Znak minus oznacza stan związany. Energia jonizacji z poziomu podstawowego to $13{,}6$ eV."),

 dict(id="M11-03", modul="M11", rozdzial="37",
  pytanie="Pasmo zabronione (przerwa energetyczna) w półprzewodniku:",
  odp=["Jest na tyle wąskie, że wzbudzenie termiczne przenosi elektrony do pasma przewodnictwa",
       "Jest szersze niż w izolatorze",
       "Nie występuje w ogóle",
       "Zanika w temperaturze zera bezwzględnego"],
  ok=0,
  wyj="W metalu pasma się nakładają, w izolatorze przerwa jest zbyt duża. Półprzewodnik leży pomiędzy — stąd silna zależność przewodnictwa od temperatury."),

 dict(id="M11-04", modul="M11", rozdzial="38",
  pytanie="Prawo rozpadu promieniotwórczego ma postać:",
  odp=[r"$N(t) = N_0 e^{-\lambda t}$", r"$N(t) = N_0 e^{\lambda t}$",
       r"$N(t) = \frac{N_0}{\lambda t}$", r"$N(t) = N_0(1 - \lambda t)$"],
  ok=0,
  wyj=r"Czas połowicznego rozpadu wiąże się ze stałą rozpadu: $T_{1/2} = \frac{\ln 2}{\lambda}$. Rozpad jest procesem losowym, niezależnym od warunków zewnętrznych."),

 dict(id="M11-05", modul="M11", rozdzial="38",
  pytanie="Niedobór masy jądra atomowego odpowiada:",
  odp=[r"Energii wiązania, zgodnie z $E = \Delta m c^2$",
       "Błędowi pomiaru masy protonu",
       "Masie elektronów w atomie",
       "Energii kinetycznej nukleonów"],
  ok=0,
  wyj="Masa jądra jest mniejsza od sumy mas nukleonów. Różnica to energia potrzebna do rozerwania jądra. Największa energia wiązania na nukleon przypada na żelazo."),

 dict(id="M11-06", modul="M11", rozdzial="38",
  pytanie="Rozpad beta minus polega na przemianie:",
  odp=["Neutronu w proton z emisją elektronu i antyneutrina",
       "Protonu w neutron z emisją pozytonu",
       "Jądra w cząstkę alfa i jądro potomne",
       "Elektronu w foton"],
  ok=0,
  wyj=r"Liczba masowa się nie zmienia, liczba atomowa rośnie o 1. Rozpad $\beta^+$ to przemiana odwrotna, a rozpad $\alpha$ oznacza emisję jądra helu."),
]
