# -*- coding: utf-8 -*-
"""Moduł IX, rozdziały 28-31: optyka geometryczna i falowa. CC BY-SA 4.0."""

P = [
 dict(id="M9o-01", modul="M9", rozdzial="28.1",
  pytanie="Współczynnik załamania ośrodka jest równy:",
  odp=["Stosunkowi prędkości światła w próżni do prędkości w tym ośrodku",
       "Stosunkowi prędkości w ośrodku do prędkości w próżni",
       "Iloczynowi obu prędkości",
       "Różnicy prędkości"],
  ok=0,
  wyj=r"$n = c/v$, więc zawsze $n \geq 1$. Dla wody wynosi około 1,33, dla szkła 1,5."),

 dict(id="M9o-02", modul="M9", rozdzial="28.2.2",
  pytanie="Promień przechodzi z wody do powietrza. Co się dzieje z kątem?",
  odp=["Oddala się od normalnej", "Zbliża się do normalnej",
       "Nie zmienia się", "Zawsze wynosi 90 stopni"],
  ok=0,
  wyj="Przejście do ośrodka rzadszego optycznie oddala promień od normalnej. Powyżej kąta granicznego następuje całkowite wewnętrzne odbicie."),

 dict(id="M9o-03", modul="M9", rozdzial="28.2.2",
  pytanie="Na czym opiera się działanie światłowodu?",
  odp=["Na całkowitym wewnętrznym odbiciu",
       "Na załamaniu światła", "Na dyfrakcji", "Na polaryzacji"],
  ok=0,
  wyj="Rdzeń ma wyższy współczynnik załamania niż płaszcz, więc światło padające pod dużym kątem nie wychodzi na zewnątrz."),

 dict(id="M9o-04", modul="M9", rozdzial="28.2.3",
  pytanie="Przedmiot ustawiono dokładnie w ognisku soczewki skupiającej. Gdzie powstanie obraz?",
  odp=["W nieskończoności — promienie wychodzą równolegle",
       "W ognisku po drugiej stronie",
       "W tej samej odległości co przedmiot",
       "Obraz nie powstanie w ogóle, bo soczewka nie działa"],
  ok=0,
  wyj=r"Z równania soczewki przy $x = f$ mamy $1/y = 0$, czyli $y \to \infty$. Tak działa kolimator i latarka z żarówką w ognisku."),

 dict(id="M9o-05", modul="M9", rozdzial="28.2.3",
  pytanie="Soczewka rozpraszająca tworzy obraz:",
  odp=["Zawsze pozorny, prosty i pomniejszony",
       "Zawsze rzeczywisty i odwrócony",
       "Rzeczywisty tylko przy bliskim przedmiocie",
       "Powiększony i odwrócony"],
  ok=0,
  wyj="To niezależne od położenia przedmiotu. Dlatego takie soczewki stosuje się w okularach dla krótkowidzów."),

 dict(id="M9o-06", modul="M9", rozdzial="28.3",
  pytanie="Oko krótkowzroczne koryguje się soczewką:",
  odp=["Rozpraszającą, o ujemnej zdolności skupiającej",
       "Skupiającą, o dodatniej zdolności",
       "Cylindryczną", "Żadną, wystarczy ćwiczenie oka"],
  ok=0,
  wyj="Oko krótkowzroczne skupia obraz przed siatkówką, więc trzeba osłabić układ. Dalekowzroczność koryguje się soczewką skupiającą."),

 dict(id="M9o-07", modul="M9", rozdzial="29.1",
  pytanie="Warunkiem obserwacji trwałego obrazu interferencyjnego jest:",
  odp=["Spójność źródeł, czyli stała różnica faz",
       "Jednakowa amplituda fal",
       "Bardzo duża odległość źródeł",
       "Użycie światła białego"],
  ok=0,
  wyj="Dwie zwykłe żarówki nie dadzą prążków, bo ich fazy zmieniają się chaotycznie. Dlatego w doświadczeniu Younga używa się jednego źródła rozdzielonego na dwie szczeliny."),

 dict(id="M9o-08", modul="M9", rozdzial="29.1",
  pytanie="Co się stanie z odstępem prążków w doświadczeniu Younga, gdy zwiększymy odległość między szczelinami?",
  odp=["Prążki zagęszczą się", "Prążki się rozsuną",
       "Nic się nie zmieni", "Prążki znikną"],
  ok=0,
  wyj=r"$\Delta y = \lambda L/d$ — odstęp jest odwrotnie proporcjonalny do odległości szczelin."),

 dict(id="M9o-09", modul="M9", rozdzial="29.4",
  pytanie="Dlaczego plama oleju na wodzie mieni się barwami?",
  odp=["Bo dla różnych długości fali warunek wzmocnienia spełniony jest przy różnej grubości warstwy",
       "Bo olej pochłania część barw",
       "Bo olej rozprasza światło",
       "Bo olej świeci własnym światłem"],
  ok=0,
  wyj="To interferencja w cienkiej warstwie. Ten sam efekt wykorzystują powłoki antyodblaskowe na obiektywach."),

 dict(id="M9o-10", modul="M9", rozdzial="30.1",
  pytanie="Dyfrakcja jest tym wyraźniejsza, im:",
  odp=["Rozmiar przeszkody bliższy jest długości fali",
       "Przeszkoda jest większa",
       "Fala ma mniejszą amplitudę",
       "Światło jest jaśniejsze"],
  ok=0,
  wyj="Dlatego dźwięk łatwo omija przeszkody, a światło prawie nie. Długość fali dźwiękowej to metry, świetlnej — setki nanometrów."),

 dict(id="M9o-11", modul="M9", rozdzial="30.2",
  pytanie="Zwężono szczelinę w doświadczeniu dyfrakcyjnym. Co stanie się z obrazem?",
  odp=["Maksimum centralne stanie się szersze",
       "Maksimum centralne zwęzi się",
       "Obraz zniknie",
       "Prążki przesuną się w bok"],
  ok=0,
  wyj="To nieintuicyjne: mniejsza szczelina daje szerszy obraz. Stąd ograniczenie zdolności rozdzielczej przyrządów optycznych."),

 dict(id="M9o-12", modul="M9", rozdzial="30.5",
  pytanie="Siatka dyfrakcyjna z większą liczbą rys na milimetr daje:",
  odp=["Węższe i lepiej rozdzielone maksima",
       "Szersze maksima",
       "Mniej barw",
       "Słabszy obraz bez zmiany szerokości"],
  ok=0,
  wyj="Zdolność rozdzielcza rośnie z liczbą oświetlonych szczelin. Dlatego siatka bije pryzmat w spektroskopii."),

 dict(id="M9o-13", modul="M9", rozdzial="30.6",
  pytanie="Dlaczego do badania struktury kryształów używa się promieni X, a nie światła widzialnego?",
  odp=["Bo ich długość fali jest porównywalna z odległościami między atomami",
       "Bo są jaśniejsze",
       "Bo łatwiej je wytworzyć",
       "Bo nie ulegają dyfrakcji"],
  ok=0,
  wyj="Odległości międzyatomowe to dziesiąte części nanometra, a światło widzialne ma setki nanometrów — za grubo, by cokolwiek rozróżnić."),

 dict(id="M9o-14", modul="M9", rozdzial="31.1",
  pytanie="Którego zjawiska NIE da się zaobserwować dla fal dźwiękowych w powietrzu?",
  odp=["Polaryzacji", "Dyfrakcji", "Interferencji", "Odbicia"],
  ok=0,
  wyj="Polaryzacja dotyczy wyłącznie fal poprzecznych, a dźwięk w powietrzu jest podłużny. To najprostszy dowód, że światło jest falą poprzeczną."),

 dict(id="M9o-15", modul="M9", rozdzial="31.2",
  pytanie="Światło niespolaryzowane przechodzi przez idealny polaryzator. Jaka część natężenia przechodzi?",
  odp=["Połowa", "Całość", "Jedna czwarta", "Nic"],
  ok=0,
  wyj="Uśrednienie cos² po wszystkich kątach daje ½. Dopiero za drugim polaryzatorem obowiązuje prawo Malusa z konkretnym kątem."),

 dict(id="M9o-16", modul="M9", rozdzial="31.3",
  pytanie="Przy kącie Brewstera światło odbite jest:",
  odp=["Całkowicie spolaryzowane liniowo",
       "Niespolaryzowane",
       "Całkowicie pochłonięte",
       "Spolaryzowane kołowo"],
  ok=0,
  wyj=r"Zachodzi to, gdy promień odbity i załamany tworzą kąt prosty, czyli $\tan\theta_B = n$. Dlatego okulary polaryzacyjne tłumią odblaski z mokrej jezdni."),
]
