# -*- coding: utf-8 -*-
"""Moduly M6-M8: elektrostatyka, prad, magnetyzm, indukcja, fale EM. CC BY-SA 4.0."""

P = [
 # ---------------- M6: ELEKTROSTATYKA ----------------
 dict(id="M6-01", modul="M6", rozdzial="17",
  pytanie="Prawo Coulomba w próżni ma postać:",
  odp=[r"$F = \frac{1}{4\pi\varepsilon_0}\frac{q_1 q_2}{r^2}$", r"$F = \frac{1}{4\pi\varepsilon_0}\frac{q_1 q_2}{r}$",
       r"$F = 4\pi\varepsilon_0 \frac{q_1 q_2}{r^2}$", r"$F = \frac{\varepsilon_0 q_1 q_2}{r^2}$"],
  ok=0,
  wyj=r"Zależność od $r^{-2}$ taka sama jak w grawitacji, ale siła elektryczna może być odpychająca. $\varepsilon_0 \approx 8{,}85\cdot10^{-12}\ \mathrm{F/m}$."),

 dict(id="M6-02", modul="M6", rozdzial="18",
  pytanie="Prawo Gaussa dla pola elektrycznego zapisujemy jako:",
  odp=[r"$\oint \vec{E}\cdot d\vec{A} = \frac{Q}{\varepsilon_0}$", r"$\oint \vec{E}\cdot d\vec{A} = \varepsilon_0 Q$",
       r"$\oint \vec{E}\cdot d\vec{s} = \frac{Q}{\varepsilon_0}$", r"$\oint \vec{E}\cdot d\vec{A} = 0$"],
  ok=0,
  wyj="Strumień pola przez powierzchnię zamkniętą zależy tylko od ładunku wewnątrz, nie od jego rozmieszczenia ani od ładunków na zewnątrz."),

 dict(id="M6-03", modul="M6", rozdzial="18",
  pytanie="Natężenie pola wewnątrz naładowanego przewodnika w równowadze elektrostatycznej wynosi:",
  odp=["Zero", r"$\frac{Q}{\varepsilon_0}$", "Tyle samo co na powierzchni", "Rośnie liniowo od środka"],
  ok=0,
  wyj="Gdyby pole było niezerowe, ładunki by się przemieszczały i nie byłoby równowagi. Cały ładunek gromadzi się na powierzchni — na tym polega klatka Faradaya."),

 dict(id="M6-04", modul="M6", rozdzial="19",
  pytanie="Związek między natężeniem pola a potencjałem to:",
  odp=[r"$\vec{E} = -\nabla V$", r"$\vec{E} = \nabla V$", r"$V = -\nabla \vec{E}$", r"$\vec{E} = -\frac{V}{r}$"],
  ok=0,
  wyj="Pole jest skierowane w stronę malejącego potencjału. Powierzchnie ekwipotencjalne są zawsze prostopadłe do linii pola."),

 dict(id="M6-05", modul="M6", rozdzial="20",
  pytanie="Pojemność kondensatora płaskiego wynosi:",
  odp=[r"$C = \frac{\varepsilon_0 \varepsilon_r S}{d}$", r"$C = \frac{\varepsilon_0 S d}{\varepsilon_r}$",
       r"$C = \frac{d}{\varepsilon_0 S}$", r"$C = \varepsilon_0 S d$"],
  ok=0,
  wyj=r"Wstawienie dielektryka o $\varepsilon_r > 1$ zwiększa pojemność. Zmniejszenie odstępu też, ale rośnie ryzyko przebicia."),

 dict(id="M6-06", modul="M6", rozdzial="20",
  pytanie="Energia zgromadzona w kondensatorze to:",
  odp=[r"$W = \tfrac{1}{2}CU^2$", r"$W = CU^2$", r"$W = \tfrac{1}{2}CU$", r"$W = \frac{C}{2U^2}$"],
  ok=0,
  wyj=r"Równoważnie $W = \frac{Q^2}{2C} = \tfrac{1}{2}QU$. Energia jest zmagazynowana w polu elektrycznym między okładkami."),

 # ---------------- M7: PRAD I POLE MAGNETYCZNE ----------------
 dict(id="M7-01", modul="M7", rozdzial="21",
  pytanie="Prawo Ohma w postaci lokalnej (materiałowej) brzmi:",
  odp=[r"$\vec{j} = \sigma \vec{E}$", r"$\vec{j} = \frac{\vec{E}}{\sigma}$",
       r"$\vec{E} = \sigma \vec{j}^2$", r"$\vec{j} = \sigma \vec{E}^2$"],
  ok=0,
  wyj=r"$\sigma$ to przewodność właściwa, $\vec{j}$ — gęstość prądu. Postać obwodowa $U = RI$ jest tego szczególnym przypadkiem."),

 dict(id="M7-02", modul="M7", rozdzial="21",
  pytanie="Moc wydzielana na oporniku wynosi:",
  odp=[r"$P = I^2 R$", r"$P = \frac{I}{R^2}$", r"$P = IR$", r"$P = \frac{R}{I^2}$"],
  ok=0,
  wyj=r"Równoważnie $P = UI = \frac{U^2}{R}$. Prawo Joule'a-Lenza: energia zamienia się w ciepło proporcjonalnie do kwadratu prądu."),

 dict(id="M7-03", modul="M7", rozdzial="22",
  pytanie="Siła Lorentza działająca na ładunek w polu magnetycznym to:",
  odp=[r"$\vec{F} = q\vec{v}\times\vec{B}$", r"$\vec{F} = q\vec{v}\cdot\vec{B}$",
       r"$\vec{F} = \frac{q\vec{v}}{\vec{B}}$", r"$\vec{F} = qB^2\vec{v}$"],
  ok=0,
  wyj="Siła jest prostopadła do prędkości i do pola, więc nie wykonuje pracy — zmienia kierunek ruchu, nie energię. Ładunek porusza się po okręgu lub linii śrubowej."),

 dict(id="M7-04", modul="M7", rozdzial="23",
  pytanie="Prawo Ampère'a w postaci całkowej brzmi:",
  odp=[r"$\oint \vec{B}\cdot d\vec{l} = \mu_0 I$", r"$\oint \vec{B}\cdot d\vec{A} = \mu_0 I$",
       r"$\oint \vec{B}\cdot d\vec{l} = \frac{I}{\mu_0}$", r"$\oint \vec{B}\cdot d\vec{l} = 0$"],
  ok=0,
  wyj=r"Całka po konturze zamkniętym zależy od prądu objętego konturem. Maxwell uzupełnił to prawo o człon z prądem przesunięcia."),

 dict(id="M7-05", modul="M7", rozdzial="23",
  pytanie="Indukcja pola magnetycznego wewnątrz długiego solenoidu wynosi:",
  odp=[r"$B = \mu_0 n I$", r"$B = \frac{\mu_0 I}{2\pi r}$", r"$B = \mu_0 n I^2$", r"$B = \frac{\mu_0 n}{I}$"],
  ok=0,
  wyj=r"$n$ to liczba zwojów na jednostkę długości. Dla prostoliniowego przewodnika obowiązuje $B = \frac{\mu_0 I}{2\pi r}$."),

 dict(id="M7-06", modul="M7", rozdzial="22",
  pytanie="Strumień pola magnetycznego przez powierzchnię zamkniętą zawsze wynosi zero, ponieważ:",
  odp=["Nie istnieją monopole magnetyczne",
       "Pole magnetyczne jest zawsze słabe",
       "Linie pola są zawsze proste",
       "Ładunek magnetyczny znosi się parami"],
  ok=0,
  wyj=r"$\oint \vec{B}\cdot d\vec{A} = 0$ to jedno z równań Maxwella. Linie pola magnetycznego są zamknięte — nie mają początku ani końca."),

 # ---------------- M8: INDUKCJA I FALE EM ----------------
 dict(id="M8-01", modul="M8", rozdzial="24",
  pytanie="Prawo indukcji Faradaya zapisujemy jako:",
  odp=[r"$\varepsilon = -\frac{d\Phi_B}{dt}$", r"$\varepsilon = -\frac{d\Phi_B}{dx}$",
       r"$\varepsilon = \frac{\Phi_B}{t}$", r"$\varepsilon = -\Phi_B t$"],
  ok=0,
  wyj="Siła elektromotoryczna zależy od szybkości zmiany strumienia, a nie od jego wartości. Znak minus to reguła Lenza."),

 dict(id="M8-02", modul="M8", rozdzial="24",
  pytanie="Reguła Lenza mówi, że prąd indukcyjny:",
  odp=["Przeciwdziała przyczynie, która go wywołała",
       "Zawsze płynie zgodnie z kierunkiem pola",
       "Ma wartość proporcjonalną do strumienia",
       "Zanika natychmiast po powstaniu"],
  ok=0,
  wyj="To konsekwencja zasady zachowania energii. Gdyby prąd wzmacniał przyczynę, dostalibyśmy energię z niczego."),

 dict(id="M8-03", modul="M8", rozdzial="25",
  pytanie="Częstotliwość drgań własnych obwodu LC wynosi:",
  odp=[r"$f = \frac{1}{2\pi\sqrt{LC}}$", r"$f = 2\pi\sqrt{LC}$",
       r"$f = \frac{1}{\sqrt{LC}}$", r"$f = \frac{\sqrt{LC}}{2\pi}$"],
  ok=0,
  wyj=r"Energia przechodzi cyklicznie z pola elektrycznego kondensatora w pole magnetyczne cewki. To elektryczny odpowiednik wahadła."),

 dict(id="M8-04", modul="M8", rozdzial="26",
  pytanie="Które równanie Maxwella opisuje powstawanie pola magnetycznego?",
  odp=[r"$\nabla\times\vec{B} = \mu_0\vec{J} + \mu_0\varepsilon_0\frac{\partial\vec{E}}{\partial t}$",
       r"$\nabla\cdot\vec{E} = \frac{\rho}{\varepsilon_0}$",
       r"$\nabla\cdot\vec{B} = 0$",
       r"$\nabla\times\vec{E} = -\frac{\partial\vec{B}}{\partial t}$"],
  ok=0,
  wyj=r"To prawo Ampère'a-Maxwella. Drugi człon, prąd przesunięcia, jest wkładem Maxwella i to on umożliwił przewidzenie fal elektromagnetycznych."),

 dict(id="M8-05", modul="M8", rozdzial="27",
  pytanie="Prędkość fal elektromagnetycznych w próżni wynika ze wzoru:",
  odp=[r"$c = \frac{1}{\sqrt{\varepsilon_0\mu_0}}$", r"$c = \sqrt{\varepsilon_0\mu_0}$",
       r"$c = \frac{\varepsilon_0}{\mu_0}$", r"$c = \frac{1}{\varepsilon_0\mu_0}$"],
  ok=0,
  wyj="Z dwóch stałych mierzonych w doświadczeniach elektrycznych i magnetycznych wychodzi prędkość światła. To był argument, że światło jest falą elektromagnetyczną."),

 dict(id="M8-06", modul="M8", rozdzial="27",
  pytanie="W fali elektromagnetycznej wektory pola elektrycznego i magnetycznego są:",
  odp=["Wzajemnie prostopadłe i prostopadłe do kierunku rozchodzenia się fali",
       "Równoległe do siebie i do kierunku ruchu fali",
       "Prostopadłe do siebie, ale równoległe do kierunku ruchu",
       "Ustawione pod kątem 45 stopni"],
  ok=0,
  wyj="Fala elektromagnetyczna jest poprzeczna. Dlatego da się ją spolaryzować, w odróżnieniu od fali dźwiękowej, która jest podłużna."),
]
