# -*- coding: utf-8 -*-
"""Moduł II, rozdziały 7-10: praca, energia, pęd, zderzenia. CC BY-SA 4.0."""

P = [
 dict(id="M2e-01", modul="M2", rozdzial="7.1",
  pytanie="Człowiek niesie walizkę poziomo ze stałą prędkością. Jaką pracę wykonuje siła, którą ją podtrzymuje?",
  odp=["Zerową, bo siła jest prostopadła do przesunięcia",
       "Równą iloczynowi ciężaru i drogi",
       "Ujemną", "Zależną od masy walizki i czasu"],
  ok=0,
  wyj=r"Praca to iloczyn skalarny, a $\cos 90^\circ = 0$. Zmęczenie bierze się z pracy mięśni na poziomie fizjologicznym, nie z pracy w sensie mechanicznym."),

 dict(id="M2e-02", modul="M2", rozdzial="7.1",
  pytanie="Kiedy praca siły jest ujemna?",
  odp=["Gdy kąt między siłą a przesunięciem jest większy od 90°",
       "Gdy siła jest mała", "Gdy ciało się nie porusza", "Nigdy, praca zawsze jest dodatnia"],
  ok=0,
  wyj="Tak jest przy tarciu i przy hamowaniu. Ujemna praca oznacza, że siła odbiera ciału energię."),

 dict(id="M2e-03", modul="M2", rozdzial="7.3",
  pytanie="Samochód zwiększa prędkość z 30 do 60 km/h. Jak zmienia się jego energia kinetyczna?",
  odp=["Rośnie czterokrotnie", "Rośnie dwukrotnie", "Rośnie ośmiokrotnie", "Rośnie o 30 jednostek"],
  ok=0,
  wyj=r"Energia zależy od $v^2$. To dlatego droga hamowania z 60 km/h jest czterokrotnie dłuższa niż z 30 km/h."),

 dict(id="M2e-04", modul="M2", rozdzial="7.3",
  pytanie="Twierdzenie o pracy i energii kinetycznej mówi, że:",
  odp=["Praca wypadkowej siły równa się przyrostowi energii kinetycznej",
       "Praca każdej siły równa się energii potencjalnej",
       "Energia kinetyczna jest zawsze zachowana",
       "Praca jest równa mocy razy droga"],
  ok=0,
  wyj="To wypadkowa, a nie pojedyncza siła. Jeśli ciało porusza się ze stałą prędkością, praca wypadkowej wynosi zero, choć poszczególne siły pracują."),

 dict(id="M2e-05", modul="M2", rozdzial="7.4",
  pytanie=r"Silnik o mocy 60 kW ciągnie pojazd ze stałą prędkością 20 m/s. Jaka jest siła napędowa?",
  odp=[r"3000 N", r"1200 N", r"300 N", r"120000 N"],
  ok=0,
  wyj=r"$P = Fv$, więc $F = 60000/20 = 3000$ N. Przy stałej prędkości ta siła równoważy opory ruchu."),

 dict(id="M2e-06", modul="M2", rozdzial="8.1",
  pytanie="Które z wymienionych sił NIE są zachowawcze?",
  odp=["Tarcie i opór powietrza", "Grawitacja", "Siła sprężystości", "Siła elektrostatyczna"],
  ok=0,
  wyj="Praca tarcia po drodze zamkniętej nie znika, tylko rośnie. Dlatego dla tarcia nie istnieje energia potencjalna."),

 dict(id="M2e-07", modul="M2", rozdzial="8.2",
  pytanie="Poziom zerowy energii potencjalnej grawitacji:",
  odp=["Można wybrać dowolnie, bo liczą się tylko różnice energii",
       "Musi być na powierzchni Ziemi",
       "Musi być w środku Ziemi",
       "Jest jednoznacznie określony przez prawa fizyki"],
  ok=0,
  wyj="Wybór poziomu odniesienia jest kwestią wygody. W zadaniach przy powierzchni zwykle bierzemy podłogę, w zagadnieniach kosmicznych nieskończoność."),

 dict(id="M2e-08", modul="M2", rozdzial="8.3",
  pytanie="Ciało zsuwa się bez tarcia po równi z wysokości h. Od czego zależy prędkość u podnóża?",
  odp=["Tylko od wysokości h", "Od kąta nachylenia równi", "Od masy ciała", "Od długości równi"],
  ok=0,
  wyj=r"Z zachowania energii $v = \sqrt{2gh}$. Kąt wpływa na czas zjazdu i przyspieszenie, ale nie na prędkość końcową."),

 dict(id="M2e-09", modul="M2", rozdzial="8.4",
  pytanie="Klocek zsuwa się po równi z tarciem. Gdzie podziewa się brakująca energia mechaniczna?",
  odp=["Zamienia się w energię wewnętrzną — ciepło",
       "Znika bezpowrotnie, zasada zachowania energii nie obowiązuje",
       "Zamienia się w energię potencjalną",
       "Przechodzi w energię kinetyczną obrotu Ziemi"],
  ok=0,
  wyj="Zasada zachowania energii obowiązuje zawsze. Nie zachowuje się jedynie energia MECHANICZNA, gdy działają siły niezachowawcze."),

 dict(id="M2e-10", modul="M2", rozdzial="9.1",
  pytanie="Działo o masie 800 kg wystrzeliwuje pocisk 4 kg z prędkością 400 m/s. Jaka jest prędkość odrzutu?",
  odp=["2 m/s", "4 m/s", "1 m/s", "8 m/s"],
  ok=0,
  wyj=r"$0 = m_1 v_1 + m_2 v_2$, stąd $v = 4\cdot400/800 = 2$ m/s w przeciwną stronę."),

 dict(id="M2e-11", modul="M2", rozdzial="9.1",
  pytanie="Dlaczego poduszka powietrzna zmniejsza obrażenia przy zderzeniu?",
  odp=["Wydłuża czas zmiany pędu, więc siła jest mniejsza",
       "Zmniejsza zmianę pędu ciała",
       "Zwiększa masę pasażera",
       "Pochłania całą energię kinetyczną"],
  ok=0,
  wyj=r"Zmiana pędu jest taka sama, bo pasażer i tak musi wyhamować. Z $F\Delta t = \Delta p$ wynika, że dłuższy czas to mniejsza siła."),

 dict(id="M2e-12", modul="M2", rozdzial="9.2",
  pytanie="Gdzie znajduje się środek masy układu dwóch kul o masach 1 kg i 3 kg odległych o 4 m?",
  odp=["1 m od cięższej kuli", "2 m od każdej", "1 m od lżejszej kuli", "3 m od cięższej"],
  ok=0,
  wyj=r"Środek masy leży bliżej większej masy: $x = \frac{1\cdot4 + 3\cdot0}{4} = 1$ m od kuli 3 kg."),

 dict(id="M2e-13", modul="M2", rozdzial="10.1",
  pytanie="W zderzeniu doskonale sprężystym zachowane są:",
  odp=["Pęd i energia kinetyczna", "Tylko pęd",
       "Tylko energia kinetyczna", "Ani pęd, ani energia"],
  ok=0,
  wyj="To definicja zderzenia sprężystego. W niesprężystym pęd nadal się zachowuje, a energia kinetyczna maleje."),

 dict(id="M2e-14", modul="M2", rozdzial="10.1",
  pytanie="Piłka odbija się sprężyście od nieruchomej ściany. Co dzieje się z jej pędem?",
  odp=["Zmienia zwrot na przeciwny, a wartość pozostaje ta sama",
       "Nie zmienia się wcale", "Maleje do zera", "Rośnie dwukrotnie"],
  ok=0,
  wyj=r"Zmiana pędu wynosi $2mv$, a przejmuje ją Ziemia razem ze ścianą. Ze względu na ogromną masę Ziemi jej prędkość zmienia się niemierzalnie."),

 dict(id="M2e-15", modul="M2", rozdzial="10.1",
  pytanie="Ciało o masie m uderza sprężyście w spoczywające ciało o tej samej masie. Co się dzieje?",
  odp=["Pierwsze zatrzymuje się, drugie rusza z prędkością pierwszego",
       "Oba poruszają się z połową prędkości",
       "Pierwsze odbija się do tyłu",
       "Oba się zatrzymują"],
  ok=0,
  wyj="Równe masy przy zderzeniu sprężystym wymieniają się prędkościami. To zasada działania kołyski Newtona."),

 dict(id="M2e-16", modul="M2", rozdzial="10.3",
  pytanie="Jaką część energii kinetycznej traci ciało przy doskonale niesprężystym zderzeniu z identycznym ciałem w spoczynku?",
  odp=["Połowę", "Całość", "Jedną czwartą", "Nic nie traci"],
  ok=0,
  wyj=r"Po zderzeniu wspólna prędkość to $v/2$, a masa $2m$. Energia: $\tfrac{1}{2}(2m)(v/2)^2 = \tfrac{1}{4}mv^2$, czyli połowa początkowej."),
]
