# -*- coding: utf-8 -*-
"""Moduł VI, rozdziały 17-20: pole elektryczne, prawo Gaussa, potencjał, kondensatory. CC BY-SA 4.0."""

P = [
 dict(id="M6e-01", modul="M6", rozdzial="17.1",
  pytanie="Zasada zachowania ładunku mówi, że:",
  odp=["Całkowity ładunek układu izolowanego jest stały",
       "Ładunek dodatni nie może zamienić się w ujemny",
       "Ładunek zawsze rośnie",
       "Ładunek jest zachowany tylko w przewodnikach"],
  ok=0,
  wyj="Ładunki mogą powstawać wyłącznie parami o przeciwnych znakach. Przy elektryzowaniu przez tarcie ładunek nie powstaje, tylko przemieszcza się między ciałami."),

 dict(id="M6e-02", modul="M6", rozdzial="17.2",
  pytanie="Odległość między dwoma ładunkami punktowymi zmniejszono trzykrotnie. Jak zmieniła się siła?",
  odp=["Wzrosła dziewięciokrotnie", "Wzrosła trzykrotnie",
       "Zmalała dziewięciokrotnie", "Nie zmieniła się"],
  ok=0,
  wyj=r"Siła zależy od $1/r^2$. Ta sama zależność co w grawitacji, ale stała jest o około 39 rzędów wielkości większa."),

 dict(id="M6e-03", modul="M6", rozdzial="17.3",
  pytanie="Linie pola elektrycznego:",
  odp=["Zaczynają się na ładunkach dodatnich, a kończą na ujemnych i nigdy się nie przecinają",
       "Tworzą zawsze zamknięte pętle",
       "Mogą się przecinać w silnym polu",
       "Są zawsze liniami prostymi"],
  ok=0,
  wyj="Przecięcie oznaczałoby dwa kierunki pola w jednym punkcie, co jest niemożliwe. Zamknięte pętle tworzą linie pola magnetycznego, nie elektrostatycznego."),

 dict(id="M6e-04", modul="M6", rozdzial="18.2",
  pytanie="Zamkniętą powierzchnią otoczono ładunek. Co się stanie ze strumieniem pola, gdy powierzchnię powiększymy dwukrotnie?",
  odp=["Nie zmieni się", "Wzrośnie dwukrotnie", "Zmaleje dwukrotnie", "Wzrośnie czterokrotnie"],
  ok=0,
  wyj="Strumień zależy wyłącznie od objętego ładunku. Pole maleje, ale powierzchnia rośnie dokładnie tak, by iloczyn pozostał stały."),

 dict(id="M6e-05", modul="M6", rozdzial="18.3.2",
  pytanie="Jakie jest natężenie pola wewnątrz naładowanej metalowej kuli w równowadze?",
  odp=["Zero", "Największe w środku", "Rośnie liniowo od środka", "Stałe i niezerowe"],
  ok=0,
  wyj="Gdyby pole było niezerowe, ładunki by się przemieszczały. To podstawa ekranowania elektrostatycznego, czyli klatki Faradaya."),

 dict(id="M6e-06", modul="M6", rozdzial="18.4.2",
  pytanie="Jak zmienia się pole nieskończonej naładowanej płaszczyzny wraz z odległością?",
  odp=["Nie zmienia się", "Maleje jak 1/r", "Maleje jak 1/r²", "Rośnie liniowo"],
  ok=0,
  wyj="Dla płaszczyzny pole jest jednorodne. To wyjaśnia, dlaczego w kondensatorze płaskim pole między okładkami jest wszędzie takie samo."),

 dict(id="M6e-07", modul="M6", rozdzial="18.4.3",
  pytanie="Dlaczego piorunochron ma ostro zakończony szpic?",
  odp=["Bo przy dużej krzywiźnie gęstość ładunku i natężenie pola są największe",
       "Bo ostrze lepiej przewodzi prąd",
       "Bo ostrze jest tańsze w produkcji",
       "Bo zmniejsza to opór elektryczny"],
  ok=0,
  wyj="Ładunek gromadzi się gęściej tam, gdzie promień krzywizny mniejszy. Silne pole przy ostrzu jonizuje powietrze i ułatwia wyładowanie."),

 dict(id="M6e-08", modul="M6", rozdzial="19.1",
  pytanie="Praca sił pola elektrostatycznego przy przeniesieniu ładunku po drodze zamkniętej wynosi:",
  odp=["Zero", "Iloczyn ładunku i napięcia", "Zawsze wartość dodatnią", "Zależy od kształtu drogi"],
  ok=0,
  wyj="Pole elektrostatyczne jest zachowawcze, więc praca nie zależy od drogi. Nie dotyczy to wirowego pola indukowanego przez zmienne pole magnetyczne."),

 dict(id="M6e-09", modul="M6", rozdzial="19.2",
  pytanie="Jaki jest związek między powierzchniami ekwipotencjalnymi a liniami pola?",
  odp=["Są zawsze wzajemnie prostopadłe",
       "Są zawsze równoległe",
       "Tworzą kąt 45 stopni",
       "Nie ma między nimi związku"],
  ok=0,
  wyj="Gdyby pole miało składową wzdłuż powierzchni ekwipotencjalnej, przesunięcie po niej wymagałoby pracy, a z definicji jej nie wymaga."),

 dict(id="M6e-10", modul="M6", rozdzial="19.2",
  pytanie=r"Elektron przeszedł różnicę potencjałów 1 V. Jaką energię uzyskał?",
  odp=[r"1 elektronowolt, czyli $1{,}6\cdot10^{-19}$ J", r"1 J",
       r"$1{,}6\cdot10^{19}$ J", r"Zero, bo elektron jest ujemny"],
  ok=0,
  wyj="Elektronowolt to jednostka energii wygodna w fizyce atomowej i jądrowej, nie jednostka napięcia."),

 dict(id="M6e-11", modul="M6", rozdzial="20.1",
  pytanie="Od czego zależy pojemność kondensatora płaskiego?",
  odp=["Od powierzchni okładek, odległości między nimi i dielektryka",
       "Od zgromadzonego ładunku",
       "Od przyłożonego napięcia",
       "Od natężenia prądu ładowania"],
  ok=0,
  wyj="Pojemność to cecha geometryczna. Ładunek i napięcie zmieniają się razem, ale ich stosunek pozostaje stały."),

 dict(id="M6e-12", modul="M6", rozdzial="20.1",
  pytanie="Trzy kondensatory po 3 μF połączono równolegle. Jaka jest pojemność zastępcza?",
  odp=["9 μF", "1 μF", "3 μF", "27 μF"],
  ok=0,
  wyj="Przy połączeniu równoległym pojemności się dodają, przy szeregowym dodają się odwrotności. To odwrotnie niż przy opornikach."),

 dict(id="M6e-13", modul="M6", rozdzial="20.2",
  pytanie=r"Napięcie na kondensatorze podwojono. Jak zmieniła się zgromadzona energia?",
  odp=["Wzrosła czterokrotnie", "Wzrosła dwukrotnie",
       "Nie zmieniła się", "Wzrosła ośmiokrotnie"],
  ok=0,
  wyj=r"$W = \tfrac{1}{2}CU^2$ — energia rośnie z kwadratem napięcia, podczas gdy ładunek tylko liniowo."),

 dict(id="M6e-14", modul="M6", rozdzial="20.3",
  pytanie="Do naładowanego i ODŁĄCZONEGO od źródła kondensatora wsunięto dielektryk. Co się stanie?",
  odp=["Napięcie zmaleje, bo ładunek jest stały, a pojemność rośnie",
       "Napięcie wzrośnie",
       "Ładunek wzrośnie",
       "Nic się nie zmieni"],
  ok=0,
  wyj=r"Odłączony kondensator ma stały ładunek, więc z $U = Q/C$ napięcie maleje. Gdyby pozostał podłączony do źródła, stałe byłoby napięcie, a wzrósłby ładunek."),

 dict(id="M6e-15", modul="M6", rozdzial="20.3",
  pytanie="Czym jest polaryzacja dielektryka?",
  odp=["Uporządkowaniem dipoli cząsteczkowych pod wpływem pola zewnętrznego",
       "Przepływem swobodnych ładunków przez dielektryk",
       "Trwałym naładowaniem dielektryka",
       "Zjawiskiem zachodzącym tylko w przewodnikach"],
  ok=0,
  wyj="Ładunki w dielektryku są związane i tylko przesuwają się nieznacznie. Powstałe pole wewnętrzne osłabia pole zewnętrzne, co zwiększa pojemność."),

 dict(id="M6e-16", modul="M6", rozdzial="20.2",
  pytanie="Gdzie zgromadzona jest energia naładowanego kondensatora?",
  odp=["W polu elektrycznym między okładkami",
       "Na powierzchni okładek",
       "W przewodach doprowadzających",
       "W dielektryku, ale tylko gdy jest metalowy"],
  ok=0,
  wyj="Gęstość energii pola elektrycznego wynosi ½ε₀E². Dlatego kondensator odłączony od źródła pozostaje niebezpieczny, dopóki pole nie zniknie."),
]
