# -*- coding: utf-8 -*-
"""Moduł IV, rozdziały 13-14: fale sprężyste, statyka i dynamika płynów. CC BY-SA 4.0."""

P = [
 dict(id="M4f-01", modul="M4", rozdzial="13.1",
  pytanie="Czym różni się fala podłużna od poprzecznej?",
  odp=["W podłużnej cząstki drgają wzdłuż kierunku ruchu fali, w poprzecznej prostopadle",
       "Podłużna rozchodzi się szybciej",
       "Poprzeczna nie przenosi energii",
       "Podłużna istnieje tylko w ciałach stałych"],
  ok=0,
  wyj="Dźwięk w powietrzu jest podłużny, fala na strunie poprzeczna. W cieczach i gazach fale poprzeczne mechaniczne nie istnieją, bo brak sprężystości postaciowej."),

 dict(id="M4f-02", modul="M4", rozdzial="13.1",
  pytanie="Co przenosi fala biegnąca przez ośrodek?",
  odp=["Energię i pęd, bez transportu materii",
       "Materię wraz z energią",
       "Wyłącznie materię",
       "Ani energii, ani materii"],
  ok=0,
  wyj="Cząstki ośrodka drgają wokół położeń równowagi i nie wędrują z falą. Korek na wodzie unosi się i opada, ale nie płynie z falą."),

 dict(id="M4f-03", modul="M4", rozdzial="13.3",
  pytanie="Fala dźwiękowa przechodzi z powietrza do wody. Co się nie zmienia?",
  odp=["Częstotliwość", "Długość fali", "Prędkość", "Amplituda"],
  ok=0,
  wyj="Częstotliwość narzuca źródło i nie zmienia się na granicy ośrodków. Skoro v rośnie, a f jest stała, to długość fali musi wzrosnąć."),

 dict(id="M4f-04", modul="M4", rozdzial="13.3",
  pytanie="Od czego zależy prędkość fali w napiętej strunie?",
  odp=["Od siły naciągu i gęstości liniowej struny",
       "Od częstotliwości drgań",
       "Od amplitudy",
       "Od długości struny"],
  ok=0,
  wyj=r"$v=\sqrt{F/\mu}$. Dlatego strojenie gitary polega na zmianie naciągu, a grubsze struny dają niższe dźwięki."),

 dict(id="M4f-05", modul="M4", rozdzial="13.5.1",
  pytanie="W fali stojącej w węzłach:",
  odp=["Amplituda drgań jest zawsze zerowa",
       "Amplituda jest największa",
       "Energia jest największa",
       "Cząstki poruszają się najszybciej"],
  ok=0,
  wyj="Węzły to punkty wygaszania, strzałki to punkty wzmocnienia. Odległość między sąsiednimi węzłami wynosi pół długości fali."),

 dict(id="M4f-06", modul="M4", rozdzial="13.5.1",
  pytanie="Piszczałka otwarta z obu stron o długości L wydaje ton podstawowy o długości fali:",
  odp=[r"$2L$", r"$4L$", r"$L$", r"$L/2$"],
  ok=0,
  wyj=r"Na obu otwartych końcach są strzałki, więc mieści się pół fali. W piszczałce zamkniętej z jednej strony ton podstawowy ma $\lambda = 4L$, czyli jest o oktawę niższy."),

 dict(id="M4f-07", modul="M4", rozdzial="13.7",
  pytanie="Dwa kamertony o częstotliwościach 440 i 444 Hz zabrzmiały jednocześnie. Ile dudnień usłyszymy na sekundę?",
  odp=["4", "2", "884", "442"],
  ok=0,
  wyj="Częstotliwość dudnień to różnica częstotliwości. Strojenie instrumentu polega na doprowadzeniu tej różnicy do zera."),

 dict(id="M4f-08", modul="M4", rozdzial="13.8",
  pytanie="Nieruchome źródło dźwięku, obserwator zbliża się. Co słyszy?",
  odp=["Dźwięk o wyższej częstotliwości niż emitowany",
       "Dźwięk o niższej częstotliwości",
       "Dźwięk niezmieniony",
       "Ciszę"],
  ok=0,
  wyj="Obserwator napotyka więcej frontów falowych w jednostce czasu. Wzory dla ruchu źródła i ruchu obserwatora są różne, bo ośrodek wyróżnia układ odniesienia."),

 dict(id="M4f-09", modul="M4", rozdzial="14.1",
  pytanie="Od czego zależy ciśnienie hydrostatyczne na danej głębokości?",
  odp=["Od gęstości cieczy i głębokości", "Od kształtu naczynia",
       "Od całkowitej objętości cieczy", "Od pola dna naczynia"],
  ok=0,
  wyj=r"$p = \rho g h$. To paradoks hydrostatyczny: wąska rurka i szerokie naczynie o tej samej wysokości dają to samo ciśnienie na dnie."),

 dict(id="M4f-10", modul="M4", rozdzial="14.2",
  pytanie="Prasa hydrauliczna ma tłoki o powierzchniach 1 cm² i 100 cm². Jaką siłę uzyskamy na dużym tłoku, naciskając mały siłą 50 N?",
  odp=["5000 N", "50 N", "500 N", "0,5 N"],
  ok=0,
  wyj=r"Ciśnienie jest jednakowe, więc siła rośnie w stosunku powierzchni. Ceną jest droga: duży tłok przesunie się sto razy mniej."),

 dict(id="M4f-11", modul="M4", rozdzial="14.3",
  pytanie="Ciało pływa zanurzone w połowie objętości. Jaka jest jego gęstość względem cieczy?",
  odp=["Połowa gęstości cieczy", "Taka sama", "Dwukrotnie większa", "Nie da się określić"],
  ok=0,
  wyj="Przy pływaniu wypór równoważy ciężar, więc stosunek gęstości równa się zanurzonej części objętości. Stąd lód wystaje z wody mniej więcej w jednej dziesiątej."),

 dict(id="M4f-12", modul="M4", rozdzial="14.3",
  pytanie="Ciało zanurzono głębiej w tej samej cieczy. Jak zmieni się siła wyporu?",
  odp=["Nie zmieni się, o ile ciało jest całe zanurzone",
       "Wzrośnie z głębokością",
       "Zmaleje z głębokością",
       "Zależy od kształtu ciała"],
  ok=0,
  wyj=r"Wypór zależy tylko od objętości wypartej cieczy i jej gęstości, nie od głębokości. Rośnie ciśnienie, ale rośnie na górze i na dole tak samo."),

 dict(id="M4f-13", modul="M4", rozdzial="14.4",
  pytanie="Rura zwęża się dwukrotnie pod względem promienia. Jak zmienia się prędkość przepływu?",
  odp=["Rośnie czterokrotnie", "Rośnie dwukrotnie",
       "Maleje dwukrotnie", "Nie zmienia się"],
  ok=0,
  wyj=r"Przekrój zależy od kwadratu promienia, więc maleje czterokrotnie. Z równania ciągłości prędkość rośnie czterokrotnie."),

 dict(id="M4f-14", modul="M4", rozdzial="14.5",
  pytanie="Dlaczego dwie łodzie płynące blisko siebie równolegle są ku sobie przyciągane?",
  odp=["Woda między nimi płynie szybciej, więc ciśnienie tam maleje",
       "Działa między nimi siła grawitacji",
       "Woda między nimi zwalnia, zwiększając ciśnienie",
       "To złudzenie optyczne"],
  ok=0,
  wyj="To skutek prawa Bernoulliego. Z tego samego powodu przechodzień może zostać wciągnięty pod rozpędzony pociąg."),

 dict(id="M4f-15", modul="M4", rozdzial="14.5",
  pytanie="Równanie Bernoulliego jest w istocie zapisem:",
  odp=["Zasady zachowania energii dla płynu",
       "Zasady zachowania pędu",
       "Prawa Pascala",
       "Prawa Archimedesa"],
  ok=0,
  wyj="Trzy człony to odpowiedniki energii ciśnienia, kinetycznej i potencjalnej, odniesione do jednostki objętości."),

 dict(id="M4f-16", modul="M4", rozdzial="14.6",
  pytanie="Samolot zwiększa prędkość dwukrotnie przy niezmienionym kącie natarcia. Jak zmieni się siła nośna?",
  odp=["Wzrośnie czterokrotnie", "Wzrośnie dwukrotnie",
       "Nie zmieni się", "Wzrośnie ośmiokrotnie"],
  ok=0,
  wyj="Siła nośna rośnie z kwadratem prędkości. Dlatego start wymaga rozbiegu, a lądowanie klap zwiększających powierzchnię i krzywiznę skrzydła."),
]
