# -*- coding: utf-8 -*-
"""Moduly M1-M3: kinematyka, dynamika, zasady zachowania, ruch obrotowy i drgania.

Tresc na licencji CC BY-SA 4.0 — utwor pochodny podrecznika Z. Kakola "Fizyka dla inzynierow".
Wzory zapisujemy w $...$ — narzedzia/wzory.py sklada je do PNG.
"""

P = [
 # ---------------- M1: KINEMATYKA I DYNAMIKA ----------------
 dict(id="M1-01", modul="M1", rozdzial="2.3",
  pytanie="Który wzór opisuje położenie w ruchu jednostajnie zmiennym?",
  odp=[r"$x = x_0 + v_0 t + \tfrac{1}{2}at^2$", r"$x = x_0 + vt$",
       r"$x = x_0 + \tfrac{1}{2}at$", r"$x = v_0 t^2 + at$"],
  ok=0,
  wyj=r"Przy stałym przyspieszeniu prędkość rośnie liniowo, $v = v_0 + at$, a droga jest całką z prędkości, stąd człon $\tfrac{1}{2}at^2$. Wzór $x = x_0 + vt$ obowiązuje tylko przy stałej prędkości."),

 dict(id="M1-02", modul="M1", rozdzial="1.2.3",
  pytanie=r"Iloczyn skalarny wektorów $\vec{a}$ i $\vec{b}$ wynosi:",
  odp=[r"$ab\cos\theta$", r"$ab\sin\theta$", r"$\tfrac{a}{b}\cos\theta$", r"$a^2+b^2$"],
  ok=0,
  wyj=r"Iloczyn skalarny daje liczbę: $\vec{a}\cdot\vec{b} = ab\cos\theta$. Iloczyn wektorowy ma moduł $ab\sin\theta$ i jest wektorem prostopadłym do obu."),

 dict(id="M1-03", modul="M1", rozdzial="3.2",
  pytanie="Dla rzutu ukośnego bez oporu powietrza zasięg jest największy przy kącie:",
  odp=[r"$45^\circ$", r"$30^\circ$", r"$60^\circ$", r"$90^\circ$"],
  ok=0,
  wyj=r"Zasięg wynosi $z = \frac{v_0^2 \sin 2\alpha}{g}$ i osiąga maksimum, gdy $\sin 2\alpha = 1$, czyli dla $\alpha = 45^\circ$. Kąty dopełniające do $90^\circ$ dają ten sam zasięg."),

 dict(id="M1-04", modul="M1", rozdzial="3.3",
  pytanie="Przyspieszenie dośrodkowe w ruchu jednostajnym po okręgu wyraża się wzorem:",
  odp=[r"$a = \frac{v^2}{r}$", r"$a = \frac{v}{r^2}$", r"$a = \frac{r}{v^2}$", r"$a = vr$"],
  ok=0,
  wyj=r"$a = \frac{v^2}{r} = \omega^2 r$. Jest skierowane do środka okręgu i zmienia kierunek prędkości, nie jej wartość."),

 dict(id="M1-05", modul="M1", rozdzial="4.2",
  pytanie="Druga zasada dynamiki Newtona w postaci ogólnej brzmi:",
  odp=[r"$\vec{F} = \frac{d\vec{p}}{dt}$", r"$\vec{F} = m\vec{v}$",
       r"$\vec{F} = \frac{d\vec{v}}{dt}$", r"$\vec{F} = \frac{m}{a}$"],
  ok=0,
  wyj=r"Postać ogólna wiąże siłę z szybkością zmiany pędu. Dopiero przy stałej masie upraszcza się do $\vec{F} = m\vec{a}$ — przy zmiennej masie, np. w rakiecie, tamta postać zawodzi."),

 dict(id="M1-06", modul="M1", rozdzial="4.2",
  pytanie="Trzecia zasada dynamiki mówi, że siły akcji i reakcji:",
  odp=["Mają równe wartości, przeciwne zwroty i przyłożone są do różnych ciał",
       "Mają równe wartości i przyłożone są do tego samego ciała",
       "Równoważą się, więc żadne ciało nie przyspiesza",
       "Występują tylko przy zderzeniach sprężystych"],
  ok=0,
  wyj="Kluczowe jest to, że działają na dwa różne ciała — dlatego się nie znoszą i każde z ciał może przyspieszać."),

 dict(id="M1-07", modul="M1", rozdzial="5.1.1",
  pytanie="Maksymalna siła tarcia statycznego wynosi:",
  odp=[r"$T = \mu_s N$", r"$T = \mu_s mg\sin\alpha$", r"$T = \frac{N}{\mu_s}$", r"$T = \mu_s v$"],
  ok=0,
  wyj=r"Siła tarcia zależy od siły nacisku $N$, a nie od powierzchni styku. Tarcie kinetyczne jest zwykle mniejsze: $\mu_k < \mu_s$."),

 dict(id="M1-08", modul="M1", rozdzial="6",
  pytanie="Prawo powszechnego ciążenia Newtona zapisujemy jako:",
  odp=[r"$F = G\frac{m_1 m_2}{r^2}$", r"$F = G\frac{m_1 m_2}{r}$",
       r"$F = G\frac{m_1 + m_2}{r^2}$", r"$F = \frac{G r^2}{m_1 m_2}$"],
  ok=0,
  wyj=r"Siła maleje z kwadratem odległości. Stała grawitacji $G \approx 6{,}67\cdot10^{-11}\,\mathrm{N\,m^2/kg^2}$."),

 dict(id="M1-09", modul="M1", rozdzial="6",
  pytanie="Pierwsza prędkość kosmiczna to prędkość, przy której ciało:",
  odp=["Krąży po orbicie kołowej tuż nad powierzchnią Ziemi",
       "Opuszcza układ Ziemia–Słońce",
       "Ucieka z pola grawitacyjnego Ziemi",
       "Spada swobodnie z zerowym przyspieszeniem"],
  ok=0,
  wyj=r"Pierwsza prędkość kosmiczna wynosi ok. $7{,}9$ km/s i wynika z warunku $\frac{mv^2}{R} = \frac{GMm}{R^2}$. Ucieczce z pola odpowiada druga prędkość kosmiczna, ok. $11{,}2$ km/s."),

 dict(id="M1-10", modul="M1", rozdzial="5.2",
  pytanie="Siła bezwładności występuje:",
  odp=["Wyłącznie w nieinercjalnych układach odniesienia",
       "W każdym układzie odniesienia",
       "Tylko przy ruchu po okręgu",
       "Tylko w polu grawitacyjnym"],
  ok=0,
  wyj="Siły bezwładności, np. odśrodkowa czy Coriolisa, nie mają źródła w oddziaływaniu ciał. Pojawiają się dopiero, gdy opisujemy ruch z układu przyspieszającego."),

 # ---------------- M2: PRACA, ENERGIA, PED ----------------
 dict(id="M2-01", modul="M2", rozdzial="7",
  pytanie="Praca siły zmiennej na drodze od A do B to:",
  odp=[r"$W = \int_A^B \vec{F}\cdot d\vec{s}$", r"$W = \vec{F}\cdot\vec{s}$",
       r"$W = \frac{F}{s}$", r"$W = \int_A^B F\,dt$"],
  ok=0,
  wyj=r"Dla siły stałej całka upraszcza się do $W = Fs\cos\theta$. Całka po czasie z siły to popęd, a nie praca."),

 dict(id="M2-02", modul="M2", rozdzial="7",
  pytanie="Energia kinetyczna ciała o masie m i prędkości v wynosi:",
  odp=[r"$E_k = \tfrac{1}{2}mv^2$", r"$E_k = mv$", r"$E_k = \tfrac{1}{2}mv$", r"$E_k = m v^2$"],
  ok=0,
  wyj=r"Twierdzenie o pracy i energii: $W = \Delta E_k$. Praca wypadkowej siły równa się przyrostowi energii kinetycznej."),

 dict(id="M2-03", modul="M2", rozdzial="8",
  pytanie="Siła jest zachowawcza, gdy:",
  odp=["Praca na drodze zamkniętej wynosi zero",
       "Zawsze jest skierowana do środka układu",
       "Jej wartość nie zależy od położenia",
       "Nie wykonuje żadnej pracy"],
  ok=0,
  wyj=r"Dla sił zachowawczych $\oint \vec{F}\cdot d\vec{s} = 0$ i można zdefiniować energię potencjalną. Tarcie tego warunku nie spełnia."),

 dict(id="M2-04", modul="M2", rozdzial="8",
  pytanie="Energia potencjalna sprężystości sprężyny o stałej k wynosi:",
  odp=[r"$E_p = \tfrac{1}{2}kx^2$", r"$E_p = kx$", r"$E_p = \tfrac{1}{2}kx$", r"$E_p = kx^2$"],
  ok=0,
  wyj=r"Wynika z całkowania siły sprężystości $F = -kx$ (prawo Hooke'a). Znak minus oznacza, że siła działa przeciwnie do wychylenia."),

 dict(id="M2-05", modul="M2", rozdzial="9",
  pytanie="Zasada zachowania pędu obowiązuje, gdy:",
  odp=["Wypadkowa sił zewnętrznych działających na układ wynosi zero",
       "Wszystkie zderzenia w układzie są sprężyste",
       "Energia kinetyczna układu jest stała",
       "Ciała poruszają się po liniach prostych"],
  ok=0,
  wyj="Pęd zachowuje się także w zderzeniach niesprężystych, w których energia kinetyczna maleje. To dwa niezależne warunki."),

 dict(id="M2-06", modul="M2", rozdzial="10",
  pytanie="W zderzeniu doskonale niesprężystym:",
  odp=["Zachowany jest pęd, ale energia kinetyczna maleje",
       "Zachowany jest pęd i energia kinetyczna",
       "Zachowana jest energia kinetyczna, ale pęd nie",
       "Nie zachowuje się ani pęd, ani energia"],
  ok=0,
  wyj="Ciała łączą się i poruszają razem. Część energii kinetycznej przechodzi w energię wewnętrzną i odkształcenie. Pęd zachowuje się zawsze, gdy nie ma sił zewnętrznych."),

 dict(id="M2-07", modul="M2", rozdzial="9",
  pytanie="Popęd siły jest równy:",
  odp=[r"$\vec{J} = \int \vec{F}\,dt = \Delta\vec{p}$", r"$\vec{J} = \vec{F}\cdot\vec{s}$",
       r"$\vec{J} = m\vec{a}$", r"$\vec{J} = \tfrac{1}{2}mv^2$"],
  ok=0,
  wyj="Popęd to zmiana pędu. Dlatego przy tej samej zmianie pędu dłuższy czas działania oznacza mniejszą siłę — na tym polega działanie poduszki powietrznej."),

 dict(id="M2-08", modul="M2", rozdzial="8",
  pytanie="Moc chwilową można zapisać jako:",
  odp=[r"$P = \vec{F}\cdot\vec{v}$", r"$P = \frac{W}{F}$", r"$P = \frac{F}{t}$", r"$P = \vec{F}\cdot\vec{s}$"],
  ok=0,
  wyj=r"Moc to szybkość wykonywania pracy, $P = \frac{dW}{dt}$, co dla siły i prędkości daje iloczyn skalarny. Jednostką jest wat."),

 # ---------------- M3: RUCH OBROTOWY I DRGANIA ----------------
 dict(id="M3-01", modul="M3", rozdzial="11",
  pytanie="Druga zasada dynamiki dla ruchu obrotowego ma postać:",
  odp=[r"$\vec{M} = I\vec{\varepsilon}$", r"$\vec{M} = m\vec{a}$",
       r"$\vec{M} = I\vec{\omega}$", r"$\vec{M} = \frac{I}{\varepsilon}$"],
  ok=0,
  wyj=r"Moment siły $M$ odgrywa rolę siły, moment bezwładności $I$ rolę masy, a przyspieszenie kątowe $\varepsilon$ rolę przyspieszenia liniowego."),

 dict(id="M3-02", modul="M3", rozdzial="11",
  pytanie="Moment bezwładności jednorodnej kuli względem osi przez środek wynosi:",
  odp=[r"$I = \tfrac{2}{5}mR^2$", r"$I = \tfrac{1}{2}mR^2$", r"$I = mR^2$", r"$I = \tfrac{1}{12}mL^2$"],
  ok=0,
  wyj=r"Dla walca pełnego $I = \tfrac{1}{2}mR^2$, dla obręczy $I = mR^2$, dla pręta względem środka $I = \tfrac{1}{12}mL^2$. Im dalej masa od osi, tym większy moment bezwładności."),

 dict(id="M3-03", modul="M3", rozdzial="11",
  pytanie="Energia kinetyczna ciała obracającego się wokół stałej osi to:",
  odp=[r"$E_k = \tfrac{1}{2}I\omega^2$", r"$E_k = \tfrac{1}{2}I\omega$",
       r"$E_k = I\omega^2$", r"$E_k = \tfrac{1}{2}mR\omega^2$"],
  ok=0,
  wyj=r"Pełna analogia do $\tfrac{1}{2}mv^2$. Przy toczeniu dochodzi jeszcze człon postępowy — energia rozdziela się na ruch środka masy i obrót."),

 dict(id="M3-04", modul="M3", rozdzial="11",
  pytanie="Moment pędu bryły sztywnej wyraża się wzorem:",
  odp=[r"$\vec{L} = I\vec{\omega}$", r"$\vec{L} = m\vec{v}$",
       r"$\vec{L} = I\vec{\varepsilon}$", r"$\vec{L} = \tfrac{1}{2}I\omega^2$"],
  ok=0,
  wyj=r"Przy zerowym wypadkowym momencie sił $\vec{L}$ jest stały. Dlatego łyżwiarka przyciągająca ręce zmniejsza $I$ i zwiększa $\omega$."),

 dict(id="M3-05", modul="M3", rozdzial="12",
  pytanie="Równanie ruchu harmonicznego prostego ma postać:",
  odp=[r"$\frac{d^2x}{dt^2} + \omega^2 x = 0$", r"$\frac{dx}{dt} + \omega x = 0$",
       r"$\frac{d^2x}{dt^2} = \omega^2 x$", r"$\frac{d^2x}{dt^2} + \omega x^2 = 0$"],
  ok=0,
  wyj=r"Rozwiązaniem jest $x(t) = A\sin(\omega t + \varphi)$. Warunkiem jest siła proporcjonalna do wychylenia i skierowana przeciwnie."),

 dict(id="M3-06", modul="M3", rozdzial="12",
  pytanie="Okres drgań wahadła matematycznego dla małych wychyleń wynosi:",
  odp=[r"$T = 2\pi\sqrt{\frac{l}{g}}$", r"$T = 2\pi\sqrt{\frac{g}{l}}$",
       r"$T = 2\pi\sqrt{\frac{m}{k}}$", r"$T = \frac{1}{2\pi}\sqrt{\frac{l}{g}}$"],
  ok=0,
  wyj=r"Okres nie zależy od masy ani (dla małych kątów) od amplitudy. Dla sprężyny odpowiednikiem jest $T = 2\pi\sqrt{\frac{m}{k}}$."),

 dict(id="M3-07", modul="M3", rozdzial="12",
  pytanie="W drganiach tłumionych amplituda maleje według zależności:",
  odp=[r"$A(t) = A_0 e^{-\beta t}$", r"$A(t) = A_0 - \beta t$",
       r"$A(t) = \frac{A_0}{\beta t}$", r"$A(t) = A_0\cos\beta t$"],
  ok=0,
  wyj="Zanik jest wykładniczy. Przy dużym tłumieniu ruch przestaje być drgający i przechodzi w pełzający."),

 dict(id="M3-08", modul="M3", rozdzial="12",
  pytanie="Rezonans mechaniczny występuje, gdy częstotliwość siły wymuszającej:",
  odp=["Jest bliska częstotliwości drgań własnych układu",
       "Jest dwa razy większa od częstotliwości własnej",
       "Dąży do zera",
       "Jest dowolna, byle siła była duża"],
  ok=0,
  wyj="Przy rezonansie amplituda gwałtownie rośnie, a ogranicza ją dopiero tłumienie. Stąd wymóg rozstrojenia częstotliwości w konstrukcjach."),
]
