# -*- coding: utf-8 -*-
"""Moduł III, rozdziały 11-12: ruch obrotowy i drgania. CC BY-SA 4.0."""

P = [
 dict(id="M3o-01", modul="M3", rozdzial="11.1",
  pytanie=r"Koło o promieniu 0,4 m obraca się z prędkością kątową 10 rad/s. Ile wynosi prędkość liniowa punktu na obwodzie?",
  odp=[r"4 m/s", r"25 m/s", r"0,04 m/s", r"40 m/s"],
  ok=0,
  wyj=r"$v = \omega R = 10 \cdot 0{,}4 = 4$ m/s. Punkty bliżej osi mają mniejszą prędkość liniową przy tej samej kątowej."),

 dict(id="M3o-02", modul="M3", rozdzial="11.1",
  pytanie="Wszystkie punkty obracającej się bryły sztywnej mają jednakową:",
  odp=["Prędkość kątową", "Prędkość liniową", "Energię kinetyczną", "Drogę"],
  ok=0,
  wyj="To definicja bryły sztywnej — odległości się nie zmieniają, więc cała bryła obraca się o ten sam kąt w tym samym czasie."),

 dict(id="M3o-03", modul="M3", rozdzial="11.2",
  pytanie="Moment siły względem osi jest zerowy, gdy:",
  odp=["Linia działania siły przechodzi przez oś obrotu",
       "Siła jest prostopadła do ramienia",
       "Siła jest bardzo mała",
       "Ciało już się obraca"],
  ok=0,
  wyj="Ramię siły wynosi wtedy zero. Dlatego pchając drzwi przy zawiasach nie da się ich otworzyć."),

 dict(id="M3o-04", modul="M3", rozdzial="11.3",
  pytanie="Które ciało o tej samej masie i promieniu ma największy moment bezwładności względem osi symetrii?",
  odp=["Obręcz", "Walec pełny", "Kula pełna", "Wszystkie mają taki sam"],
  ok=0,
  wyj=r"Obręcz $mR^2$, walec $\tfrac{1}{2}mR^2$, kula $\tfrac{2}{5}mR^2$. Im dalej masa od osi, tym większy moment bezwładności."),

 dict(id="M3o-05", modul="M3", rozdzial="11.3",
  pytanie="Obręcz, walec i kula staczają się bez poślizgu z tej samej równi. Które dotrze na dół pierwsze?",
  odp=["Kula", "Obręcz", "Walec", "Dotrą jednocześnie"],
  ok=0,
  wyj="Wygrywa ciało o najmniejszym momencie bezwładności, bo mniej energii idzie na obrót, a więcej na ruch postępowy. Kolejność: kula, walec, obręcz — niezależnie od mas i promieni."),

 dict(id="M3o-06", modul="M3", rozdzial="11.3",
  pytanie="Twierdzenie Steinera pozwala obliczyć moment bezwładności:",
  odp=["Względem osi równoległej do osi przez środek masy",
       "Względem dowolnej osi przechodzącej przez środek masy",
       "Dla ciał o zmiennej masie",
       "Dla ruchu postępowego"],
  ok=0,
  wyj=r"$I = I_0 + md^2$. Moment względem osi przez środek masy jest zawsze najmniejszy z możliwych dla danego kierunku."),

 dict(id="M3o-07", modul="M3", rozdzial="11.4",
  pytanie="Ciało toczy się bez poślizgu. Jak dzieli się jego energia kinetyczna?",
  odp=["Na część postępową i obrotową",
       "Cała jest obrotowa",
       "Cała jest postępowa",
       "Zależy to wyłącznie od prędkości"],
  ok=0,
  wyj=r"$E = \tfrac{1}{2}mv^2 + \tfrac{1}{2}I\omega^2$, przy warunku toczenia $v = \omega R$. Dla walca podział wynosi 2:1 na korzyść ruchu postępowego."),

 dict(id="M3o-08", modul="M3", rozdzial="11.2.2",
  pytanie="Wirująca łyżwiarka przyciąga ręce do ciała. Co dzieje się z jej energią kinetyczną?",
  odp=["Rośnie, kosztem pracy jej mięśni",
       "Pozostaje stała, bo moment pędu się zachowuje",
       "Maleje", "Zamienia się w energię potencjalną"],
  ok=0,
  wyj=r"Moment pędu $L = I\omega$ jest stały, ale energia $\tfrac{1}{2}I\omega^2 = L^2/(2I)$ rośnie przy malejącym $I$. Ta energia pochodzi z pracy mięśni."),

 dict(id="M3o-09", modul="M3", rozdzial="12.1",
  pytanie="Warunkiem ruchu harmonicznego prostego jest siła:",
  odp=["Proporcjonalna do wychylenia i skierowana do położenia równowagi",
       "Stała co do wartości i kierunku",
       "Proporcjonalna do prędkości",
       "Odwrotnie proporcjonalna do kwadratu wychylenia"],
  ok=0,
  wyj=r"$F = -kx$. Znak minus jest istotny — siła zawsze zwraca ciało do równowagi, stąd nazwa siła zwracająca."),

 dict(id="M3o-10", modul="M3", rozdzial="12.1",
  pytanie="Gdzie w ruchu harmonicznym prędkość jest największa?",
  odp=["W położeniu równowagi", "W skrajnym wychyleniu",
       "W połowie amplitudy", "Prędkość jest stała"],
  ok=0,
  wyj="W skrajnym wychyleniu prędkość jest zerowa, a przyspieszenie największe. W równowadze odwrotnie."),

 dict(id="M3o-11", modul="M3", rozdzial="12.2",
  pytanie="Jak zmieni się okres drgań masy na sprężynie, jeśli masę zwiększymy czterokrotnie?",
  odp=["Wzrośnie dwukrotnie", "Wzrośnie czterokrotnie",
       "Zmaleje dwukrotnie", "Nie zmieni się"],
  ok=0,
  wyj=r"$T = 2\pi\sqrt{m/k}$, więc okres rośnie jak pierwiastek z masy."),

 dict(id="M3o-12", modul="M3", rozdzial="12.2.1",
  pytanie="Wahadło matematyczne przeniesiono na Księżyc, gdzie g jest sześć razy mniejsze. Jak zmieni się okres?",
  odp=[r"Wzrośnie około $\sqrt{6} \approx 2{,}45$ razy", "Wzrośnie sześciokrotnie",
       "Zmaleje sześciokrotnie", "Nie zmieni się"],
  ok=0,
  wyj=r"$T = 2\pi\sqrt{l/g}$ — okres rośnie odwrotnie do pierwiastka z przyspieszenia. Zegar wahadłowy chodziłby tam wolniej."),

 dict(id="M3o-13", modul="M3", rozdzial="12.3",
  pytanie="Amplitudę drgań harmonicznych podwojono. Jak zmieniła się energia całkowita?",
  odp=["Wzrosła czterokrotnie", "Wzrosła dwukrotnie",
       "Nie zmieniła się", "Wzrosła ośmiokrotnie"],
  ok=0,
  wyj=r"$E = \tfrac{1}{2}kA^2$ — energia rośnie z kwadratem amplitudy. Okres natomiast nie zależy od amplitudy."),

 dict(id="M3o-14", modul="M3", rozdzial="12.4",
  pytanie="Przy tłumieniu krytycznym układ:",
  odp=["Wraca do równowagi najszybciej, bez wykonywania drgań",
       "Drga z malejącą amplitudą",
       "Drga z rosnącą amplitudą",
       "Nie wraca do równowagi"],
  ok=0,
  wyj="Tłumienie mniejsze daje drgania gasnące, większe — powolny powrót bez drgań. Amortyzatory dobiera się blisko krytycznego."),

 dict(id="M3o-15", modul="M3", rozdzial="12.5",
  pytanie="Po ustaleniu się drgań wymuszonych układ drga z częstotliwością:",
  odp=["Siły wymuszającej", "Własną układu",
       "Średnią z obu", "Malejącą w czasie"],
  ok=0,
  wyj="Drgania własne wygasają po czasie przejściowym. Zostają wyłącznie drgania o częstotliwości wymuszenia, a ich amplituda zależy od odległości od rezonansu."),

 dict(id="M3o-16", modul="M3", rozdzial="12.5.1",
  pytanie="Co ogranicza amplitudę w rezonansie?",
  odp=["Tłumienie", "Masa układu", "Amplituda siły wymuszającej", "Nic, rośnie nieograniczenie"],
  ok=0,
  wyj="Bez tłumienia amplituda teoretycznie rosłaby nieograniczenie. W praktyce zawsze istnieją straty energii, które ją ograniczają."),
]
