# -*- coding: utf-8 -*-
"""Moduł I, rozdziały 4-6: dynamika, tarcie, siły bezwładności, grawitacja. CC BY-SA 4.0."""

P = [
 dict(id="M1d-01", modul="M1", rozdzial="4.1.1",
  pytanie="Które oddziaływanie ma największy zasięg i jest zawsze przyciągające?",
  odp=["Grawitacyjne", "Silne jądrowe", "Słabe jądrowe", "Elektromagnetyczne"],
  ok=0,
  wyj="Grawitacja jest najsłabsza, ale ma nieskończony zasięg i nie ma ładunku ujemnego, więc nie da się jej ekranować. Elektromagnetyczne też ma nieskończony zasięg, ale może odpychać."),

 dict(id="M1d-02", modul="M1", rozdzial="4.1.2",
  pytanie="Czym różni się masa bezwładna od grawitacyjnej?",
  odp=["Pojęciowo są różne, ale doświadczenia pokazują ich równość — to zasada równoważności",
       "Masa bezwładna jest zawsze większa",
       "Masa grawitacyjna zależy od miejsca, bezwładna nie",
       "To dwie nazwy tej samej wielkości zdefiniowanej tak samo"],
  ok=0,
  wyj="Bezwładna mierzy opór przed zmianą ruchu, grawitacyjna udział w przyciąganiu. Ich równość, sprawdzona z ogromną dokładnością, jest fundamentem ogólnej teorii względności."),

 dict(id="M1d-03", modul="M1", rozdzial="4.1.3",
  pytanie=r"Pęd ciała o masie 2 kg poruszającego się z prędkością 5 m/s wynosi:",
  odp=[r"$10\ \mathrm{kg\,m/s}$", r"$25\ \mathrm{kg\,m/s}$", r"$2{,}5\ \mathrm{kg\,m/s}$", r"$20\ \mathrm{kg\,m/s}$"],
  ok=0,
  wyj=r"$p = mv$. Pęd jest wektorem — ma kierunek i zwrot prędkości. Nie mylić z energią kinetyczną, która wynosi tu 25 J."),

 dict(id="M1d-04", modul="M1", rozdzial="4.2",
  pytanie="Ciało porusza się ze stałą prędkością po linii prostej. Co można powiedzieć o siłach?",
  odp=["Ich wypadkowa wynosi zero, ale pojedyncze siły mogą być niezerowe",
       "Na ciało nie działa żadna siła",
       "Działa jedna siła zgodna z kierunkiem ruchu",
       "Siły są zawsze zerowe w każdym układzie odniesienia"],
  ok=0,
  wyj="Pierwsza zasada dynamiki nie rozróżnia braku sił od ich równoważenia. Samochód jadący ze stałą prędkością ma napęd równoważony przez opory."),

 dict(id="M1d-05", modul="M1", rozdzial="4.2",
  pytanie="Koń ciągnie wóz. Siła reakcji wozu na konia jest równa co do wartości sile konia. Dlaczego układ rusza?",
  odp=["Bo siły akcji i reakcji działają na różne ciała i nie znoszą się w obrębie jednego",
       "Bo siła konia jest jednak większa",
       "Bo trzecia zasada nie obowiązuje przy ruchu",
       "Bo wóz nie działa na konia żadną siłą"],
  ok=0,
  wyj="To klasyczny paradoks. O ruchu wozu decyduje wypadkowa sił działających NA WÓZ, a siła reakcji działa na konia, nie na wóz."),

 dict(id="M1d-06", modul="M1", rozdzial="4.2",
  pytanie=r"Na ciało o masie 5 kg działają dwie prostopadłe siły 30 N i 40 N. Ile wynosi przyspieszenie?",
  odp=[r"$10\ \mathrm{m/s^2}$", r"$14\ \mathrm{m/s^2}$", r"$2\ \mathrm{m/s^2}$", r"$70\ \mathrm{m/s^2}$"],
  ok=0,
  wyj=r"Wypadkowa: $\sqrt{30^2+40^2} = 50$ N, stąd $a = 50/5 = 10\ \mathrm{m/s^2}$. Sił prostopadłych nie wolno dodawać arytmetycznie."),

 dict(id="M1d-07", modul="M1", rozdzial="5.1.1",
  pytanie="Od czego NIE zależy siła tarcia kinetycznego?",
  odp=["Od pola powierzchni styku", "Od siły nacisku",
       "Od rodzaju trących powierzchni", "Od współczynnika tarcia"],
  ok=0,
  wyj="To wynik nieintuicyjny: szersza opona nie daje większego tarcia przy tym samym nacisku. Rzeczywista powierzchnia styku na poziomie mikroskopowym zależy od nacisku, a nie od wymiarów."),

 dict(id="M1d-08", modul="M1", rozdzial="5.1.1",
  pytanie=r"Klocek spoczywa na równi. Przy jakim kącie zacznie się zsuwać?",
  odp=[r"Gdy $\tan\alpha > \mu_s$", r"Gdy $\sin\alpha > \mu_s$",
       r"Gdy $\cos\alpha > \mu_s$", r"Gdy $\alpha > 45^\circ$"],
  ok=0,
  wyj=r"Warunek: $mg\sin\alpha > \mu_s mg\cos\alpha$. Masa się skraca, więc kąt graniczny nie zależy od masy klocka."),

 dict(id="M1d-09", modul="M1", rozdzial="5.2",
  pytanie="Pasażer w ruszającym autobusie odczuwa pchnięcie do tyłu. Jak to opisać w układzie inercjalnym?",
  odp=["Ciało pasażera pozostaje w spoczynku, a oparcie napiera na niego do przodu",
       "Działa na niego realna siła skierowana do tyłu",
       "Autobus wywiera na pasażera siłę do tyłu",
       "To złudzenie bez żadnego opisu fizycznego"],
  ok=0,
  wyj="Siła bezwładności istnieje tylko w układzie związanym z autobusem. Z zewnątrz widać, że to autobus przyspiesza pod bezwładnym pasażerem."),

 dict(id="M1d-10", modul="M1", rozdzial="5.2",
  pytanie="Siła Coriolisa działa na ciało, które:",
  odp=["Porusza się w wirującym układzie odniesienia",
       "Spoczywa w wirującym układzie",
       "Porusza się ruchem jednostajnym w układzie inercjalnym",
       "Znajduje się w polu grawitacyjnym"],
  ok=0,
  wyj="Zależy od prędkości względem układu wirującego. Odpowiada za skręcanie wiatrów i za to, że cyklony na półkulach wirują przeciwnie."),

 dict(id="M1d-11", modul="M1", rozdzial="6.1",
  pytanie="Ciało przeniesiono na wysokość równą trzem promieniom Ziemi nad powierzchnię. Jak zmieni się jego ciężar?",
  odp=["Zmaleje szesnastokrotnie", "Zmaleje dziewięciokrotnie",
       "Zmaleje trzykrotnie", "Zmaleje czterokrotnie"],
  ok=0,
  wyj=r"Odległość od środka wynosi $4R$, a siła maleje jak $r^2$, więc $16$ razy. Liczy się odległość od ŚRODKA, nie wysokość nad powierzchnią."),

 dict(id="M1d-12", modul="M1", rozdzial="6.2",
  pytanie="Które prawo Keplera mówi, że kwadrat okresu obiegu jest proporcjonalny do sześcianu wielkiej półosi?",
  odp=["Trzecie", "Pierwsze", "Drugie", "Czwarte"],
  ok=0,
  wyj="Pierwsze mówi o eliptycznych orbitach z Słońcem w ognisku, drugie o stałej prędkości polowej, trzecie wiąże okres z rozmiarem orbity."),

 dict(id="M1d-13", modul="M1", rozdzial="6.2",
  pytanie="Z drugiego prawa Keplera wynika, że planeta w peryhelium porusza się:",
  odp=["Szybciej niż w aphelium", "Wolniej niż w aphelium",
       "Z taką samą prędkością", "Ruchem jednostajnym po okręgu"],
  ok=0,
  wyj="Stała prędkość polowa oznacza, że bliżej Słońca planeta musi zakreślać większy kąt w tym samym czasie. To konsekwencja zachowania momentu pędu."),

 dict(id="M1d-14", modul="M1", rozdzial="6.3",
  pytanie=r"Druga prędkość kosmiczna dla Ziemi wynosi około:",
  odp=[r"$11{,}2$ km/s", r"$7{,}9$ km/s", r"$16{,}7$ km/s", r"$3{,}0$ km/s"],
  ok=0,
  wyj=r"Pierwsza ($7{,}9$ km/s) wystarcza na orbitę kołową, druga ($11{,}2$) na ucieczkę z pola Ziemi, trzecia ($16{,}7$) z Układu Słonecznego."),

 dict(id="M1d-15", modul="M1", rozdzial="6.4",
  pytanie="Stan nieważkości na orbicie wynika z tego, że:",
  odp=["Stacja i astronauta spadają swobodnie z tym samym przyspieszeniem",
       "Na tej wysokości nie ma już grawitacji",
       "Siła odśrodkowa jest większa od grawitacji",
       "Prędkość stacji znosi grawitację"],
  ok=0,
  wyj="Na wysokości ISS grawitacja to jeszcze około 90% wartości przy powierzchni. Nieważkość to skutek swobodnego spadku, nie braku grawitacji."),

 dict(id="M1d-16", modul="M1", rozdzial="6.4",
  pytanie="Natężenie pola grawitacyjnego wyraża się w jednostkach:",
  odp=[r"$\mathrm{N/kg}$, co jest równoważne $\mathrm{m/s^2}$", r"$\mathrm{N\,m^2/kg^2}$",
       r"$\mathrm{J/kg}$", r"$\mathrm{kg/m^3}$"],
  ok=0,
  wyj=r"$\mathrm{N\,m^2/kg^2}$ to jednostka stałej $G$, a $\mathrm{J/kg}$ to potencjał grawitacyjny, czyli energia na jednostkę masy."),
]
