# -*- coding: utf-8 -*-
"""Moduł X, rozdziały 32-35: fizyka kwantowa. CC BY-SA 4.0."""

P = [
 dict(id="M10k-01", modul="M10", rozdzial="32.1",
  pytanie="Na czym polegała katastrofa w nadfiolecie?",
  odp=["Fizyka klasyczna przewidywała nieskończoną energię promieniowania ciała doskonale czarnego dla krótkich fal",
       "Nadfiolet okazał się szkodliwy dla organizmów",
       "Nie udawało się wytworzyć promieniowania nadfioletowego",
       "Nadfiolet nie ulegał dyfrakcji"],
  ok=0,
  wyj="Wzór Rayleigha-Jeansa rozbiegał się do nieskończoności. Planck rozwiązał to, zakładając kwantowanie energii promieniowania."),

 dict(id="M10k-02", modul="M10", rozdzial="32.2",
  pytanie="Temperaturę ciała doskonale czarnego podwojono. Jak zmieniła się moc promieniowania?",
  odp=["Wzrosła szesnastokrotnie", "Wzrosła dwukrotnie",
       "Wzrosła czterokrotnie", "Wzrosła ośmiokrotnie"],
  ok=0,
  wyj=r"Prawo Stefana-Boltzmanna: $P \sim T^4$. Dlatego gorące ciała stygną początkowo bardzo szybko."),

 dict(id="M10k-03", modul="M10", rozdzial="32.3",
  pytanie="Zgodnie z prawem Wiena, im gorętsze ciało, tym maksimum emisji przypada na fale:",
  odp=["Krótsze", "Dłuższe", "Zawsze te same", "Wyłącznie podczerwone"],
  ok=0,
  wyj="Dlatego chłodne gwiazdy świecą na czerwono, a gorące na niebiesko. Ciało o temperaturze pokojowej promieniuje w podczerwieni."),

 dict(id="M10k-04", modul="M10", rozdzial="32.4",
  pytanie="Zwiększono natężenie światła padającego na fotokatodę, nie zmieniając barwy. Co się stanie?",
  odp=["Popłynie więcej elektronów, ale ich maksymalna energia się nie zmieni",
       "Elektrony będą miały większą energię",
       "Nic się nie zmieni",
       "Zjawisko ustanie"],
  ok=0,
  wyj="To rozstrzygnęło spór o naturę światła. Falowo większe natężenie powinno dawać szybsze elektrony, a doświadczenie pokazuje co innego."),

 dict(id="M10k-05", modul="M10", rozdzial="32.4",
  pytanie="Poniżej częstotliwości progowej zjawisko fotoelektryczne:",
  odp=["Nie zachodzi wcale, niezależnie od natężenia i czasu naświetlania",
       "Zachodzi wolniej",
       "Zachodzi po dłuższym naświetlaniu",
       "Zachodzi tylko w metalach"],
  ok=0,
  wyj="Pojedynczy foton musi mieć dość energii, by pokonać pracę wyjścia. Nie da się zsumować energii wielu za słabych fotonów."),

 dict(id="M10k-06", modul="M10", rozdzial="32.4.1",
  pytanie=r"Praca wyjścia metalu wynosi 2 eV. Foton ma energię 5 eV. Jaka jest maksymalna energia kinetyczna elektronu?",
  odp=["3 eV", "7 eV", "2,5 eV", "5 eV"],
  ok=0,
  wyj=r"$E_k = h\nu - W = 5 - 2 = 3$ eV. Maksymalna, bo elektrony z głębszych warstw tracą część energii po drodze."),

 dict(id="M10k-07", modul="M10", rozdzial="32.5",
  pytanie="Efekt Comptona dowodzi, że foton:",
  odp=["Ma pęd i zachowuje się w zderzeniu jak cząstka",
       "Nie ma energii",
       "Jest wyłącznie falą",
       "Ma masę spoczynkową"],
  ok=0,
  wyj=r"Foton ma pęd $p = h/\lambda$, choć jego masa spoczynkowa wynosi zero. Zderzenie z elektronem opisuje się jak zderzenie sprężyste."),

 dict(id="M10k-08", modul="M10", rozdzial="33.2",
  pytanie="Dlaczego model atomu Rutherforda był sprzeczny z fizyką klasyczną?",
  odp=["Krążący elektron powinien promieniować i spaść na jądro",
       "Jądro byłoby za lekkie",
       "Atom byłby elektrycznie naładowany",
       "Elektrony odpychałyby się zbyt silnie"],
  ok=0,
  wyj="Ładunek poruszający się z przyspieszeniem promieniuje, więc elektron w ułamku nanosekundy straciłby energię. Bohr rozwiązał to postulatem o orbitach stacjonarnych."),

 dict(id="M10k-09", modul="M10", rozdzial="33.3",
  pytanie="Co jest skwantowane w modelu Bohra atomu wodoru?",
  odp=["Moment pędu elektronu", "Ładunek elektronu",
       "Masa elektronu", "Prędkość światła"],
  ok=0,
  wyj=r"$L = n\hbar$. Z tego warunku wynikają dozwolone promienie orbit i poziomy energetyczne."),

 dict(id="M10k-10", modul="M10", rozdzial="33.4",
  pytanie="Widmo emisyjne atomu wodoru jest:",
  odp=["Liniowe — złożone z pojedynczych, ostrych linii",
       "Ciągłe", "Pasmowe", "Niewidoczne"],
  ok=0,
  wyj="Skwantowane poziomy energetyczne dają ściśle określone energie fotonów. Widmo ciągłe dają rozgrzane ciała stałe, a nie pojedyncze atomy."),

 dict(id="M10k-11", modul="M10", rozdzial="34.1",
  pytanie="Dlaczego nie obserwujemy falowych własności piłki tenisowej?",
  odp=["Bo jej długość fali de Broglie'a jest o wiele rzędów wielkości mniejsza od rozmiarów przeszkód",
       "Bo piłka jest zbyt ciężka, by mieć falę",
       "Bo fale materii dotyczą tylko ładunków",
       "Bo piłka porusza się zbyt wolno"],
  ok=0,
  wyj=r"Przy $p$ rzędu kilograma razy metr na sekundę $\lambda \approx 10^{-34}$ m. Żadna przeszkoda o takim rozmiarze nie istnieje."),

 dict(id="M10k-12", modul="M10", rozdzial="34.2",
  pytanie="Doświadczenie Davissona i Germera wykazało:",
  odp=["Dyfrakcję elektronów na krysztale, czyli falową naturę materii",
       "Istnienie jądra atomowego",
       "Kwantowanie ładunku",
       "Istnienie neutronu"],
  ok=0,
  wyj="Elektrony rozpraszane na krysztale niklu dały obraz dyfrakcyjny zgodny z długością fali de Broglie'a."),

 dict(id="M10k-13", modul="M10", rozdzial="35.2",
  pytanie="Zasada nieoznaczoności wynika z:",
  odp=["Falowej natury materii, a nie z niedoskonałości przyrządów",
       "Błędów pomiarowych",
       "Wpływu obserwatora na wynik",
       "Ograniczeń technicznych, które kiedyś znikną"],
  ok=0,
  wyj="Każdy pakiet falowy o określonym położeniu musi składać się z wielu długości fal, czyli wielu pędów. To własność matematyczna fal, a nie usterka aparatury."),

 dict(id="M10k-14", modul="M10", rozdzial="35.2",
  pytanie="Im dokładniej znamy położenie cząstki, tym:",
  odp=["Mniej dokładnie znamy jej pęd",
       "Dokładniej znamy jej pęd",
       "Większa jest jej energia",
       "Mniejsza jest jej masa"],
  ok=0,
  wyj=r"$\Delta x \Delta p \geq \hbar/2$. Analogiczna relacja wiąże energię i czas życia stanu, co tłumaczy naturalną szerokość linii widmowych."),

 dict(id="M10k-15", modul="M10", rozdzial="35.3.1",
  pytanie="Rozwiązanie równania Schrödingera dla cząstki w studni potencjału daje:",
  odp=["Dyskretne, skwantowane poziomy energetyczne",
       "Dowolne wartości energii",
       "Jedną możliwą energię",
       "Energię zawsze ujemną"],
  ok=0,
  wyj="Kwantowanie pojawia się naturalnie z warunków brzegowych, bez dodatkowego postulatu. To przewaga mechaniki kwantowej nad modelem Bohra."),

 dict(id="M10k-16", modul="M10", rozdzial="35.4",
  pytanie="Zjawisko tunelowania polega na tym, że cząstka:",
  odp=["Może przeniknąć barierę potencjału wyższą niż jej energia",
       "Porusza się szybciej niż światło",
       "Znika i pojawia się w innym miejscu bez żadnego prawdopodobieństwa",
       "Traci masę przy przechodzeniu"],
  ok=0,
  wyj="Funkcja falowa nie znika gwałtownie na barierze, tylko maleje wykładniczo. Na tym opiera się mikroskop tunelowy i rozpad alfa."),
]
