# -*- coding: utf-8 -*-
"""Moduly M4-M5: fale sprezyste, plyny, termodynamika. CC BY-SA 4.0."""

P = [
 # ---------------- M4: FALE SPREZYSTE I PLYNY ----------------
 dict(id="M4-01", modul="M4", rozdzial="13",
  pytanie="Związek między prędkością, częstotliwością i długością fali to:",
  odp=[r"$v = \lambda f$", r"$v = \frac{\lambda}{f}$", r"$v = \frac{f}{\lambda}$", r"$v = \lambda f^2$"],
  ok=0,
  wyj=r"Prędkość fali zależy od ośrodka, nie od źródła. Przy przejściu do innego ośrodka zmienia się $\lambda$, a $f$ pozostaje stała."),

 dict(id="M4-02", modul="M4", rozdzial="13",
  pytanie="Prędkość fali poprzecznej w napiętej strunie wynosi:",
  odp=[r"$v = \sqrt{\frac{F}{\mu}}$", r"$v = \sqrt{\frac{\mu}{F}}$",
       r"$v = \frac{F}{\mu}$", r"$v = F\mu$"],
  ok=0,
  wyj=r"$F$ to siła naciągu, $\mu$ — masa na jednostkę długości. Mocniejsze naciągnięcie struny podnosi dźwięk, grubsza struna go obniża."),

 dict(id="M4-03", modul="M4", rozdzial="13",
  pytanie="Zjawisko Dopplera polega na tym, że:",
  odp=["Częstotliwość odbierana zmienia się przy ruchu źródła lub obserwatora",
       "Prędkość fali zależy od prędkości źródła",
       "Amplituda fali maleje z odległością",
       "Fala zmienia kierunek na granicy ośrodków"],
  ok=0,
  wyj="Przy zbliżaniu fronty falowe zagęszczają się i częstotliwość rośnie, przy oddalaniu maleje. Prędkość fali w ośrodku pozostaje bez zmian."),

 dict(id="M4-04", modul="M4", rozdzial="13",
  pytanie="Fala stojąca w strunie zamocowanej na obu końcach ma częstotliwości własne:",
  odp=[r"$f_n = \frac{nv}{2L}$", r"$f_n = \frac{nv}{4L}$", r"$f_n = \frac{v}{2nL}$", r"$f_n = \frac{nL}{2v}$"],
  ok=0,
  wyj=r"Na obu końcach muszą być węzły, więc $L = n\frac{\lambda}{2}$. Dla rury otwartej z jednej strony warunek jest inny i daje $\frac{nv}{4L}$ dla nieparzystych $n$."),

 dict(id="M4-05", modul="M4", rozdzial="14",
  pytanie="Prawo Pascala mówi, że ciśnienie wywierane na ciecz zamkniętą:",
  odp=["Przenosi się jednakowo we wszystkich kierunkach",
       "Rośnie wraz z odległością od punktu przyłożenia",
       "Działa tylko na dno naczynia",
       "Zależy od kształtu naczynia"],
  ok=0,
  wyj="Na tym opiera się działanie prasy i układów hydraulicznych. Mała siła na małym tłoku daje dużą siłę na dużym."),

 dict(id="M4-06", modul="M4", rozdzial="14",
  pytanie="Siła wyporu według prawa Archimedesa wynosi:",
  odp=[r"$F = \rho g V$", r"$F = \rho V$", r"$F = \frac{\rho g}{V}$", r"$F = mgV$"],
  ok=0,
  wyj=r"$\rho$ to gęstość płynu, $V$ — objętość zanurzonej części ciała. Wypór równa się ciężarowi wypartego płynu."),

 dict(id="M4-07", modul="M4", rozdzial="14",
  pytanie="Równanie Bernoulliego dla przepływu ustalonego cieczy doskonałej ma postać:",
  odp=[r"$p + \tfrac{1}{2}\rho v^2 + \rho g h = \mathrm{const}$",
       r"$p + \rho v^2 + \rho g h = \mathrm{const}$",
       r"$p + \tfrac{1}{2}\rho v + \rho h = \mathrm{const}$",
       r"$p\,v\,h = \mathrm{const}$"],
  ok=0,
  wyj="To zasada zachowania energii dla płynu. Gdzie prędkość rośnie, tam ciśnienie maleje — stąd siła nośna skrzydła."),

 dict(id="M4-08", modul="M4", rozdzial="14",
  pytanie="Równanie ciągłości dla cieczy nieściśliwej mówi, że:",
  odp=[r"$S_1 v_1 = S_2 v_2$", r"$S_1 v_2 = S_2 v_1$", r"$\frac{S_1}{v_1} = \frac{S_2}{v_2}$", r"$S_1 + v_1 = S_2 + v_2$"],
  ok=0,
  wyj="Strumień objętości jest stały. W zwężeniu rury ciecz płynie szybciej — to bezpośrednia konsekwencja zachowania masy."),

 # ---------------- M5: TERMODYNAMIKA ----------------
 dict(id="M5-01", modul="M5", rozdzial="15",
  pytanie="Równanie stanu gazu doskonałego to:",
  odp=[r"$pV = nRT$", r"$pV = \frac{nR}{T}$", r"$\frac{p}{V} = nRT$", r"$pV = nRT^2$"],
  ok=0,
  wyj=r"$R \approx 8{,}31\ \mathrm{J/(mol\cdot K)}$. W postaci mikroskopowej $pV = Nk_BT$, gdzie $k_B$ to stała Boltzmanna."),

 dict(id="M5-02", modul="M5", rozdzial="15",
  pytanie="Średnia energia kinetyczna ruchu postępowego cząsteczki gazu doskonałego wynosi:",
  odp=[r"$\bar{E}_k = \tfrac{3}{2}k_BT$", r"$\bar{E}_k = \tfrac{1}{2}k_BT$",
       r"$\bar{E}_k = 3k_BT$", r"$\bar{E}_k = \tfrac{3}{2}RT$"],
  ok=0,
  wyj=r"Na każdy stopień swobody przypada $\tfrac{1}{2}k_BT$ — zasada ekwipartycji. Ruch postępowy ma trzy stopnie swobody, stąd $\tfrac{3}{2}k_BT$."),

 dict(id="M5-03", modul="M5", rozdzial="16",
  pytanie="Pierwsza zasada termodynamiki w postaci różniczkowej brzmi:",
  odp=[r"$dU = \delta Q - \delta W$", r"$dU = \delta Q + \delta W$",
       r"$dU = \delta W - \delta Q$", r"$dU = \delta Q \cdot \delta W$"],
  ok=0,
  wyj="To zasada zachowania energii dla układów termodynamicznych. Ciepło dostarczone podnosi energię wewnętrzną albo idzie na pracę wykonaną przez układ."),

 dict(id="M5-04", modul="M5", rozdzial="16",
  pytanie="W przemianie izotermicznej gazu doskonałego:",
  odp=[r"$\Delta U = 0$, a całe ciepło zamienia się w pracę",
       r"$Q = 0$, a praca odbywa się kosztem energii wewnętrznej",
       "Ciśnienie jest stałe",
       "Objętość jest stała"],
  ok=0,
  wyj=r"Energia wewnętrzna gazu doskonałego zależy tylko od temperatury. Przy $T = \mathrm{const}$ mamy $\Delta U = 0$, więc $Q = W$. Przemiana bez wymiany ciepła to adiabata."),

 dict(id="M5-05", modul="M5", rozdzial="16",
  pytanie="Sprawność silnika Carnota wynosi:",
  odp=[r"$\eta = 1 - \frac{T_2}{T_1}$", r"$\eta = 1 - \frac{T_1}{T_2}$",
       r"$\eta = \frac{T_2}{T_1}$", r"$\eta = \frac{T_1 - T_2}{T_2}$"],
  ok=0,
  wyj=r"Temperatury w kelwinach, $T_1$ to źródło ciepłe. To górna granica sprawności każdego silnika cieplnego pracującego między tymi temperaturami."),

 dict(id="M5-06", modul="M5", rozdzial="16",
  pytanie="Druga zasada termodynamiki w ujęciu entropii mówi, że w układzie izolowanym:",
  odp=[r"$\Delta S \geq 0$", r"$\Delta S \leq 0$", r"$\Delta S = 0$ zawsze", r"$\Delta S$ może być dowolne"],
  ok=0,
  wyj="Entropia układu izolowanego nie maleje. Równość dotyczy procesów odwracalnych, a w rzeczywistych procesach entropia rośnie."),

 dict(id="M5-07", modul="M5", rozdzial="16",
  pytanie="Dla przemiany adiabatycznej gazu doskonałego obowiązuje:",
  odp=[r"$pV^\kappa = \mathrm{const}$", r"$pV = \mathrm{const}$",
       r"$\frac{p}{V} = \mathrm{const}$", r"$p^\kappa V = \mathrm{const}$"],
  ok=0,
  wyj=r"$\kappa = \frac{c_p}{c_V}$ to wykładnik adiabaty. Adiabata jest bardziej stroma niż izoterma, bo przy rozprężaniu gaz dodatkowo się oziębia."),

 dict(id="M5-08", modul="M5", rozdzial="15",
  pytanie="Prędkość średnia kwadratowa cząsteczek gazu wyraża się wzorem:",
  odp=[r"$v_{\mathrm{rms}} = \sqrt{\frac{3RT}{M}}$", r"$v_{\mathrm{rms}} = \sqrt{\frac{RT}{3M}}$",
       r"$v_{\mathrm{rms}} = \frac{3RT}{M}$", r"$v_{\mathrm{rms}} = \sqrt{\frac{3M}{RT}}$"],
  ok=0,
  wyj=r"$M$ to masa molowa. Lżejsze cząsteczki poruszają się szybciej w tej samej temperaturze — dlatego wodór ucieka z atmosfery, a azot nie."),
]
