# -*- coding: utf-8 -*-
"""Moduł VII, rozdziały 21-23: prąd elektryczny i pole magnetyczne. CC BY-SA 4.0."""

P = [
 dict(id="M7p-01", modul="M7", rozdzial="21.1",
  pytanie="Umowny kierunek prądu w przewodniku metalowym jest:",
  odp=["Przeciwny do rzeczywistego ruchu elektronów",
       "Zgodny z ruchem elektronów",
       "Prostopadły do ruchu elektronów",
       "Losowy"],
  ok=0,
  wyj="Umowa powstała, zanim odkryto elektron. Przyjęto kierunek ruchu ładunków dodatnich i tak zostało."),

 dict(id="M7p-02", modul="M7", rozdzial="21.2",
  pytanie="Przewodnik rozciągnięto tak, że jego długość wzrosła dwukrotnie przy stałej objętości. Jak zmienił się opór?",
  odp=["Wzrósł czterokrotnie", "Wzrósł dwukrotnie",
       "Zmalał dwukrotnie", "Nie zmienił się"],
  ok=0,
  wyj=r"Długość rośnie dwa razy, a przekrój maleje dwa razy, więc $R = \rho l/S$ rośnie czterokrotnie."),

 dict(id="M7p-03", modul="M7", rozdzial="21.2",
  pytanie="Które urządzenie NIE spełnia prawa Ohma?",
  odp=["Dioda półprzewodnikowa", "Opornik drutowy",
       "Grzałka w stałej temperaturze", "Przewód miedziany"],
  ok=0,
  wyj="Charakterystyka diody jest silnie nieliniowa. Prawo Ohma obowiązuje dla przewodników metalicznych przy stałej temperaturze."),

 dict(id="M7p-04", modul="M7", rozdzial="21.2",
  pytanie="Dwa oporniki po 6 Ω połączono równolegle. Jaki jest opór zastępczy?",
  odp=["3 Ω", "12 Ω", "6 Ω", "1,5 Ω"],
  ok=0,
  wyj="Dla dwóch jednakowych oporników w równoległym połączeniu opór jest o połowę mniejszy. Opór zastępczy jest zawsze mniejszy od najmniejszego ze składowych."),

 dict(id="M7p-05", modul="M7", rozdzial="21.3",
  pytanie=r"Żarówka 60 W pracuje przy 230 V. Jaki płynie przez nią prąd?",
  odp=[r"około 0,26 A", r"około 3,8 A", r"około 26 A", r"około 0,038 A"],
  ok=0,
  wyj=r"$I = P/U = 60/230 \approx 0{,}26$ A. Opór żarnika wynosi wtedy około 880 Ω w stanie gorącym."),

 dict(id="M7p-06", modul="M7", rozdzial="21.3.1",
  pytanie="Dlaczego energię elektryczną przesyła się liniami wysokiego napięcia?",
  odp=["Bo przy wyższym napięciu płynie mniejszy prąd, a straty rosną z kwadratem prądu",
       "Bo wysokie napięcie szybciej się rozchodzi",
       "Bo przewody są wtedy tańsze",
       "Bo zmniejsza to opór przewodów"],
  ok=0,
  wyj=r"Straty to $I^2R$. Podniesienie napięcia dziesięciokrotnie zmniejsza prąd dziesięciokrotnie, a straty stukrotnie."),

 dict(id="M7p-07", modul="M7", rozdzial="21.4.1",
  pytanie="Napięcie na zaciskach baterii pod obciążeniem jest mniejsze od SEM, ponieważ:",
  odp=["Część napięcia odkłada się na oporze wewnętrznym",
       "SEM maleje z czasem",
       "Prąd płynie w przeciwną stronę",
       "Napięcie mierzy się nieprawidłowo"],
  ok=0,
  wyj=r"$U = \varepsilon - Ir$. Przy dużym prądzie spadek jest zauważalny — dlatego światła auta przygasają przy rozruchu."),

 dict(id="M7p-08", modul="M7", rozdzial="21.4.2",
  pytanie="Pierwsze prawo Kirchhoffa jest wyrazem zasady zachowania:",
  odp=["Ładunku", "Energii", "Pędu", "Masy"],
  ok=0,
  wyj="Ładunek nie gromadzi się w węźle, więc suma prądów wpływających równa się sumie wypływających. Drugie prawo wynika z zachowania energii."),

 dict(id="M7p-09", modul="M7", rozdzial="22.1",
  pytanie="Dlaczego siła magnetyczna nie zmienia energii kinetycznej cząstki?",
  odp=["Bo jest zawsze prostopadła do prędkości, więc nie wykonuje pracy",
       "Bo jest bardzo mała",
       "Bo działa tylko przez chwilę",
       "Bo cząstka porusza się po prostej"],
  ok=0,
  wyj="Praca to iloczyn skalarny siły i przesunięcia, a przy kącie prostym wynosi zero. Siła zmienia wyłącznie kierunek ruchu."),

 dict(id="M7p-10", modul="M7", rozdzial="22.3",
  pytanie="Cząstka naładowana wpada w pole magnetyczne równolegle do linii pola. Jak się porusza?",
  odp=["Ruchem jednostajnym prostoliniowym, bez zmiany toru",
       "Po okręgu", "Po spirali", "Zatrzymuje się"],
  ok=0,
  wyj=r"Iloczyn wektorowy $\vec{v}\times\vec{B}$ dla wektorów równoległych wynosi zero. Ruch po linii śrubowej powstaje, gdy prędkość ma obie składowe."),

 dict(id="M7p-11", modul="M7", rozdzial="22.3",
  pytanie="Od czego NIE zależy okres obiegu cząstki w polu magnetycznym?",
  odp=["Od jej prędkości", "Od masy cząstki",
       "Od ładunku cząstki", "Od indukcji pola"],
  ok=0,
  wyj=r"$T = 2\pi m/(qB)$. Szybsza cząstka zatacza większy okrąg, ale w tym samym czasie. Na tym opiera się działanie cyklotronu."),

 dict(id="M7p-12", modul="M7", rozdzial="22.4",
  pytanie="Przewodnik z prądem umieszczono równolegle do linii pola magnetycznego. Jaka siła na niego działa?",
  odp=["Zerowa", "Maksymalna", "Skierowana wzdłuż prądu", "Zależna od długości"],
  ok=0,
  wyj=r"$F = BIL\sin\alpha$, a dla $\alpha = 0$ siła znika. Maksimum występuje przy ustawieniu prostopadłym."),

 dict(id="M7p-13", modul="M7", rozdzial="22.5",
  pytanie="Do czego służy pomiar napięcia Halla?",
  odp=["Do wyznaczenia znaku i koncentracji nośników ładunku",
       "Do pomiaru oporu przewodnika",
       "Do pomiaru pojemności",
       "Do wyznaczenia temperatury"],
  ok=0,
  wyj="Znak napięcia mówi, czy nośnikami są elektrony, czy dziury. To właśnie efektem Halla potwierdzono przewodnictwo dziurowe w półprzewodnikach."),

 dict(id="M7p-14", modul="M7", rozdzial="23.1.3",
  pytanie="Jak zmienia się pole magnetyczne wokół prostoliniowego przewodnika z prądem wraz z odległością?",
  odp=["Maleje jak 1/r", "Maleje jak 1/r²", "Nie zmienia się", "Rośnie liniowo"],
  ok=0,
  wyj="To inna zależność niż dla ładunku punktowego. Wynika z symetrii walcowej i prawa Ampère'a."),

 dict(id="M7p-15", modul="M7", rozdzial="23.2",
  pytanie="Dwa równoległe przewodniki z prądami płynącymi w przeciwnych kierunkach:",
  odp=["Odpychają się", "Przyciągają się", "Nie oddziałują", "Skręcają się wzajemnie"],
  ok=0,
  wyj="Prądy zgodne przyciągają się, przeciwne odpychają. To odwrotnie niż przy ładunkach elektrycznych tego samego znaku."),

 dict(id="M7p-16", modul="M7", rozdzial="23.4",
  pytanie="Czym różni się ferromagnetyk od paramagnetyku?",
  odp=["Ferromagnetyk zachowuje namagnesowanie po usunięciu pola i wzmacnia je tysiące razy",
       "Ferromagnetyk osłabia pole zewnętrzne",
       "Paramagnetyk jest zawsze silniejszym magnesem",
       "Nie ma między nimi różnicy"],
  ok=0,
  wyj="Ferromagnetyzm wynika z uporządkowania domen magnetycznych. Powyżej temperatury Curie znika i materiał staje się paramagnetykiem."),
]
