# -*- coding: utf-8 -*-
"""Moduł I, rozdziały 1-3: wielkości fizyczne, wektory, ruch. CC BY-SA 4.0."""

P = [
 dict(id="M1k-01", modul="M1", rozdzial="1.1",
  pytanie="Które wielkości należą do podstawowych jednostek układu SI?",
  odp=["Metr, kilogram, sekunda, amper, kelwin, mol, kandela",
       "Metr, gram, sekunda, wolt, stopień Celsjusza",
       "Centymetr, gram, sekunda, dyna",
       "Metr, kilogram, sekunda, niuton, dżul"],
  ok=0,
  wyj="Jednostki podstawowych SI jest siedem. Niuton i dżul są jednostkami pochodnymi, wyprowadzonymi z podstawowych."),

 dict(id="M1k-02", modul="M1", rozdzial="1.1",
  pytanie=r"Jaki jest wymiar pracy wyrażony w jednostkach podstawowych?",
  odp=[r"$\mathrm{kg\,m^2\,s^{-2}}$", r"$\mathrm{kg\,m\,s^{-2}}$",
       r"$\mathrm{kg\,m^2\,s^{-3}}$", r"$\mathrm{kg\,m^{-1}\,s^{-2}}$"],
  ok=0,
  wyj=r"Praca to siła razy droga: $\mathrm{kg\,m\,s^{-2}} \cdot \mathrm{m}$. Dzieląc przez sekundę dostajemy moc, a mnożąc przez $\mathrm{m^{-3}}$ — ciśnienie."),

 dict(id="M1k-03", modul="M1", rozdzial="1.2.1",
  pytanie=r"Wektor o wartości 10 tworzy z osią $x$ kąt $30^\circ$. Ile wynosi jego składowa $x$?",
  odp=[r"$10\cos 30^\circ \approx 8{,}66$", r"$10\sin 30^\circ = 5$",
       r"$10\tan 30^\circ \approx 5{,}77$", r"$10$"],
  ok=0,
  wyj=r"Składowa wzdłuż osi to $a_x = a\cos\alpha$, a prostopadła $a_y = a\sin\alpha$. Suma kwadratów składowych daje kwadrat długości wektora."),

 dict(id="M1k-04", modul="M1", rozdzial="1.2.2",
  pytanie="Kiedy wartość sumy dwóch wektorów jest równa sumie ich wartości?",
  odp=["Gdy wektory mają ten sam kierunek i zwrot",
       "Gdy wektory są prostopadłe",
       "Gdy wektory mają przeciwne zwroty",
       "Zawsze, niezależnie od kierunków"],
  ok=0,
  wyj="Tylko dla wektorów równoległych i zgodnie skierowanych. Dla prostopadłych obowiązuje twierdzenie Pitagorasa, a dla przeciwnych odejmowanie."),

 dict(id="M1k-05", modul="M1", rozdzial="1.2.4",
  pytanie=r"Ile wynosi iloczyn wektorowy $\vec{a}\times\vec{a}$?",
  odp=[r"Wektor zerowy", r"$a^2$", r"$2\vec{a}$", r"Wektor o długości $a^2$ prostopadły do $\vec{a}$"],
  ok=0,
  wyj=r"Kąt między wektorem a nim samym wynosi zero, a $\sin 0 = 0$. Iloczyn wektorowy dwóch wektorów równoległych zawsze jest zerowy."),

 dict(id="M1k-06", modul="M1", rozdzial="2.1",
  pytanie="Czym różni się droga od przemieszczenia?",
  odp=["Droga to skalar równy długości toru, przemieszczenie to wektor łączący punkt początkowy z końcowym",
       "To dwa określenia tej samej wielkości",
       "Droga jest wektorem, a przemieszczenie skalarem",
       "Przemieszczenie jest zawsze większe od drogi"],
  ok=0,
  wyj="Po przebiegnięciu pełnego okrążenia stadionu droga wynosi 400 m, a przemieszczenie zero. Przemieszczenie nigdy nie jest większe od drogi."),

 dict(id="M1k-07", modul="M1", rozdzial="2.2.3",
  pytanie="Ciało przebywa połowę drogi z prędkością 60 km/h, a drugą połowę z 30 km/h. Ile wynosi prędkość średnia?",
  odp=["40 km/h", "45 km/h", "50 km/h", "35 km/h"],
  ok=0,
  wyj=r"Dla równych DRÓG prędkość średnia to średnia harmoniczna: $\frac{2 v_1 v_2}{v_1+v_2} = \frac{2\cdot60\cdot30}{90} = 40$ km/h. Średnia arytmetyczna 45 km/h byłaby poprawna przy równych CZASACH."),

 dict(id="M1k-08", modul="M1", rozdzial="2.3.2",
  pytanie="Czy ciało może mieć zerową prędkość i niezerowe przyspieszenie?",
  odp=["Tak, na przykład w najwyższym punkcie rzutu pionowego",
       "Nie, zerowa prędkość oznacza brak przyspieszenia",
       "Tak, ale tylko w ruchu po okręgu",
       "Tylko w układzie nieinercjalnym"],
  ok=0,
  wyj="W najwyższym punkcie rzutu pionowego prędkość jest zerowa, ale przyspieszenie nadal wynosi g. Prędkość i przyspieszenie są niezależne."),

 dict(id="M1k-09", modul="M1", rozdzial="2.3.3",
  pytanie="Ciało spada swobodnie bez oporu powietrza. Jak rośnie przebyta droga w kolejnych sekundach?",
  odp=["Jak kolejne liczby nieparzyste: 1, 3, 5, 7",
       "Jednakowo w każdej sekundzie",
       "Jak kolejne liczby naturalne: 1, 2, 3, 4",
       "Jak kwadraty: 1, 4, 9, 16"],
  ok=0,
  wyj=r"Droga narasta jak $t^2$, więc przyrosty w kolejnych sekundach są jak $1, 3, 5, 7$. Same drogi liczone od startu są jak kwadraty."),

 dict(id="M1k-10", modul="M1", rozdzial="2.3.3",
  pytanie=r"Które równanie wiąże prędkość z drogą przy stałym przyspieszeniu, bez udziału czasu?",
  odp=[r"$v^2 = v_0^2 + 2as$", r"$v = v_0 + at$", r"$s = v_0 t + \tfrac{1}{2}at^2$", r"$v = \tfrac{s}{t}$"],
  ok=0,
  wyj="To najwygodniejszy wzór w zadaniach o drodze hamowania, bo czas zwykle nie jest ani dany, ani szukany."),

 dict(id="M1k-11", modul="M1", rozdzial="3.1",
  pytanie="W ruchu na płaszczyźnie ruchy wzdłuż osi x i y są:",
  odp=["Niezależne od siebie i można je analizować osobno",
       "Zawsze jednakowe",
       "Powiązane tak, że nie da się ich rozdzielić",
       "Niezależne tylko przy stałej prędkości"],
  ok=0,
  wyj="To zasada niezależności ruchów Galileusza. Dlatego kula wypuszczona poziomo i upuszczona z tej samej wysokości spadną jednocześnie."),

 dict(id="M1k-12", modul="M1", rozdzial="3.2",
  pytanie=r"W rzucie ukośnym bez oporu powietrza, w najwyższym punkcie toru prędkość ciała:",
  odp=[r"Jest pozioma i równa $v_0\cos\alpha$", r"Wynosi zero",
       r"Jest pionowa i równa $v_0\sin\alpha$", r"Jest równa $v_0$"],
  ok=0,
  wyj="Zeruje się tylko składowa pionowa. Składowa pozioma jest stała przez cały lot, bo w poziomie nie działa żadna siła."),

 dict(id="M1k-13", modul="M1", rozdzial="3.2",
  pytanie=r"Dwa ciała wyrzucono z tą samą prędkością pod kątami $30^\circ$ i $60^\circ$. Co można powiedzieć o ich zasięgach?",
  odp=["Są równe", "Większy ma rzut pod 60°", "Większy ma rzut pod 30°", "Zależy to od masy ciał"],
  ok=0,
  wyj=r"Zasięg zależy od $\sin 2\alpha$, a $\sin 60^\circ = \sin 120^\circ$. Kąty dopełniające do $90^\circ$ dają ten sam zasięg, ale różny czas lotu i wysokość."),

 dict(id="M1k-14", modul="M1", rozdzial="3.3",
  pytanie=r"Okres obiegu w ruchu jednostajnym po okręgu wiąże się z prędkością kątową wzorem:",
  odp=[r"$T = \frac{2\pi}{\omega}$", r"$T = \frac{\omega}{2\pi}$", r"$T = 2\pi\omega$", r"$T = \frac{\pi}{\omega}$"],
  ok=0,
  wyj=r"Pełny obrót to kąt $2\pi$. Częstotliwość $f = 1/T = \omega/2\pi$."),

 dict(id="M1k-15", modul="M1", rozdzial="3.3",
  pytanie="Dlaczego w ruchu jednostajnym po okręgu występuje przyspieszenie, choć wartość prędkości się nie zmienia?",
  odp=["Bo zmienia się kierunek wektora prędkości",
       "Bo ciało porusza się coraz szybciej",
       "Bo działa siła odśrodkowa",
       "Przyspieszenie w tym ruchu nie występuje"],
  ok=0,
  wyj="Przyspieszenie to zmiana wektora prędkości, a wektor zmienia się także wtedy, gdy zmienia się tylko jego kierunek."),

 dict(id="M1k-16", modul="M1", rozdzial="3.4",
  pytanie="W ruchu krzywoliniowym przyspieszenie rozkłada się na składowe:",
  odp=["Styczną, zmieniającą wartość prędkości, i normalną, zmieniającą jej kierunek",
       "Poziomą i pionową, zawsze równe co do wartości",
       "Dośrodkową i odśrodkową, znoszące się wzajemnie",
       "Wyłącznie normalną"],
  ok=0,
  wyj=r"Składowa styczna $a_t = dv/dt$, normalna $a_n = v^2/R$. W ruchu jednostajnym po okręgu styczna znika."),
]
