# -*- coding: utf-8 -*-
"""Moduł XI, rozdziały 36-38: atomy wieloelektronowe, ciało stałe, fizyka jądrowa. CC BY-SA 4.0."""

P = [
 dict(id="M11j-01", modul="M11", rozdzial="36.1",
  pytanie="Ile liczb kwantowych opisuje stan elektronu w atomie?",
  odp=["Cztery: n, l, m oraz spinowa", "Dwie: n i l",
       "Trzy: n, l, m", "Jedna: n"],
  ok=0,
  wyj="Trzy pierwsze wynikają z równania Schrödingera, czwarta ze spinu. Zakaz Pauliego zabrania dwóm elektronom mieć identyczny komplet."),

 dict(id="M11j-02", modul="M11", rozdzial="36.1.1",
  pytanie="Poboczna liczba kwantowa l dla powłoki n = 3 może przyjmować wartości:",
  odp=["0, 1, 2", "1, 2, 3", "0, 1, 2, 3", "tylko 3"],
  ok=0,
  wyj=r"$l$ przyjmuje wartości od 0 do $n-1$. Odpowiadają one podpowłokom s, p, d."),

 dict(id="M11j-03", modul="M11", rozdzial="36.2",
  pytanie="Ile elektronów mieści się maksymalnie na podpowłoce p?",
  odp=["Sześć", "Dwa", "Dziesięć", "Czternaście"],
  ok=0,
  wyj=r"Dla $l = 1$ liczba $m$ przyjmuje trzy wartości, a na każdą przypadają dwa spiny. Stąd s mieści 2, p 6, d 10, f 14 elektronów."),

 dict(id="M11j-04", modul="M11", rozdzial="36.3",
  pytanie="Dlaczego gazy szlachetne są chemicznie bierne?",
  odp=["Mają całkowicie zapełnioną zewnętrzną powłokę elektronową",
       "Mają bardzo duże jądra",
       "Nie mają elektronów walencyjnych w ogóle",
       "Są zbyt lekkie"],
  ok=0,
  wyj="Zamknięta powłoka to układ o najniższej energii. Oddanie lub przyjęcie elektronu byłoby energetycznie niekorzystne."),

 dict(id="M11j-05", modul="M11", rozdzial="36.4",
  pytanie="Od czego zależy krótkofalowa granica widma ciągłego promieni X?",
  odp=["Wyłącznie od napięcia przyspieszającego w lampie",
       "Od materiału anody",
       "Od natężenia prądu w lampie",
       "Od temperatury katody"],
  ok=0,
  wyj=r"$\lambda_{min} = hc/(eU)$. Materiał anody decyduje natomiast o położeniu linii charakterystycznych."),

 dict(id="M11j-06", modul="M11", rozdzial="36.6",
  pytanie="Warunkiem działania lasera jest:",
  odp=["Inwersja obsadzeń, czyli więcej atomów w stanie wzbudzonym niż podstawowym",
       "Bardzo niska temperatura",
       "Silne pole magnetyczne",
       "Użycie wyłącznie gazów szlachetnych"],
  ok=0,
  wyj="W równowadze termicznej rozkład Boltzmanna gwarantuje przewagę stanu podstawowego. Inwersję trzeba wymusić pompowaniem."),

 dict(id="M11j-07", modul="M11", rozdzial="37.1",
  pytanie="Czym różni się przewodnik od izolatora w modelu pasmowym?",
  odp=["Szerokością przerwy energetycznej między pasmem walencyjnym a przewodnictwa",
       "Liczbą elektronów w atomie",
       "Gęstością materiału",
       "Temperaturą topnienia"],
  ok=0,
  wyj="W metalu pasma się nakładają, w izolatorze przerwa sięga kilku elektronowoltów, a w półprzewodniku jest na tyle wąska, że pokonuje ją wzbudzenie termiczne."),

 dict(id="M11j-08", modul="M11", rozdzial="37.2",
  pytanie="Jak zmienia się opór półprzewodnika samoistnego przy wzroście temperatury?",
  odp=["Maleje, bo rośnie liczba nośników",
       "Rośnie, jak w metalu",
       "Nie zmienia się",
       "Najpierw rośnie, potem gwałtownie maleje do zera"],
  ok=0,
  wyj="To odwrotnie niż w metalu, gdzie opór rośnie z temperaturą przez wzmożone rozpraszanie. Na tym opiera się działanie termistora."),

 dict(id="M11j-09", modul="M11", rozdzial="37.3",
  pytanie="Domieszkowanie krzemu fosforem, mającym pięć elektronów walencyjnych, daje półprzewodnik:",
  odp=["Typu n, z nadmiarem elektronów",
       "Typu p, z nadmiarem dziur",
       "Izolator",
       "Nadprzewodnik"],
  ok=0,
  wyj="Piąty elektron nie ma pary w wiązaniu i łatwo przechodzi do pasma przewodnictwa. Domieszka trójwartościowa, na przykład bor, daje typ p."),

 dict(id="M11j-10", modul="M11", rozdzial="37.4",
  pytanie="Złącze p-n przewodzi prąd:",
  odp=["Głównie w jednym kierunku, przy polaryzacji w kierunku przewodzenia",
       "Jednakowo w obu kierunkach",
       "Tylko przy oświetleniu",
       "Wcale"],
  ok=0,
  wyj="Warstwa zaporowa zwęża się przy polaryzacji w kierunku przewodzenia i poszerza przy zaporowej. To podstawa diody prostowniczej."),

 dict(id="M11j-11", modul="M11", rozdzial="38.1",
  pytanie="Izotopy tego samego pierwiastka różnią się:",
  odp=["Liczbą neutronów", "Liczbą protonów",
       "Liczbą elektronów w atomie obojętnym", "Ładunkiem jądra"],
  ok=0,
  wyj="Liczba protonów decyduje o pierwiastku, więc jest jednakowa. Izotopy mają te same własności chemiczne, ale różne jądrowe."),

 dict(id="M11j-12", modul="M11", rozdzial="38.2",
  pytanie="Który pierwiastek ma największą energię wiązania przypadającą na nukleon?",
  odp=["Żelazo", "Wodór", "Uran", "Hel"],
  ok=0,
  wyj="Dlatego synteza opłaca się dla pierwiastków lżejszych od żelaza, a rozszczepienie dla cięższych. Żelazo jest kresem obu dróg."),

 dict(id="M11j-13", modul="M11", rozdzial="38.3.1",
  pytanie="Podczas rozpadu alfa liczba atomowa jądra:",
  odp=["Maleje o 2, a liczba masowa o 4",
       "Rośnie o 1, a masowa się nie zmienia",
       "Maleje o 1", "Nie zmienia się"],
  ok=0,
  wyj="Cząstka alfa to jądro helu, czyli dwa protony i dwa neutrony. Przy rozpadzie beta minus liczba atomowa rośnie o 1, a masowa zostaje."),

 dict(id="M11j-14", modul="M11", rozdzial="38.3.4",
  pytanie="Po upływie dwóch okresów połowicznego rozpadu pozostaje:",
  odp=["Jedna czwarta początkowej liczby jąder", "Połowa",
       "Nic", "Jedna ósma"],
  ok=0,
  wyj="Każdy okres zmniejsza liczbę jąder o połowę, więc po dwóch zostaje ¼, po trzech ⅛. Rozpad nigdy nie kończy się całkowicie."),

 dict(id="M11j-15", modul="M11", rozdzial="38.4.1",
  pytanie="Reakcja łańcuchowa w reaktorze wymaga, by na jedno rozszczepienie przypadał:",
  odp=["Dokładnie jeden neutron wywołujący kolejne rozszczepienie",
       "Co najmniej trzy takie neutrony",
       "Zero neutronów",
       "Stały dopływ neutronów z zewnątrz"],
  ok=0,
  wyj="Współczynnik mnożenia równy jedności daje pracę ustaloną. Powyżej jedności moc rośnie lawinowo, poniżej reakcja gaśnie. Regulują to pręty pochłaniające."),

 dict(id="M11j-16", modul="M11", rozdzial="38.4.3",
  pytanie="Skąd bierze się energia wypromieniowywana przez Słońce?",
  odp=["Z syntezy jąder wodoru w hel i towarzyszącego jej ubytku masy",
       "Ze spalania wodoru w reakcji chemicznej",
       "Z rozszczepienia ciężkich jąder",
       "Z kurczenia się grawitacyjnego, które jest jedynym źródłem"],
  ok=0,
  wyj=r"Przy syntezie helu ubywa około 0,7% masy, zamienianej na energię wedle $E = \Delta mc^2$. Spalanie chemiczne wyczerpałoby Słońce w kilka tysięcy lat."),
]
